package com.wally.hiread.model.order;

import java.util.Date;
import java.util.List;

public class ProdOrder {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_prod_order.id
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_prod_order.dateCreated
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	private Date datecreated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_prod_order.dateModified
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	private Date datemodified;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_prod_order.c_amount
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	private String amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_prod_order.c_couponAmount
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	private String couponAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_prod_order.c_orderNo
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	private String orderNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_prod_order.c_usePoint
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	private String usePoint;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_prod_order.c_user_id
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_prod_order.c_netAmount
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	private String netAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_prod_order.c_paid
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	private String paid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_prod_order.c_paymentTime
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	private String paymentTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_prod_order.c_grouDiscount
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	private String grouDiscount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_prod_order.c_address_id
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	private String addressId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_prod_order.c_productDiscount
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	private String productDiscount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_prod_order.c_channel
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	private String channel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_prod_order.c_buyerMessage
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	private String buyerMessage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_prod_order.c_outTradeNo
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	private String outTradeNo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_prod_order.id
	 * @return  the value of app_fd_ec_prod_order.id
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_prod_order.id
	 * @param id  the value for app_fd_ec_prod_order.id
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_prod_order.dateCreated
	 * @return  the value of app_fd_ec_prod_order.dateCreated
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public Date getDatecreated() {
		return datecreated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_prod_order.dateCreated
	 * @param datecreated  the value for app_fd_ec_prod_order.dateCreated
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_prod_order.dateModified
	 * @return  the value of app_fd_ec_prod_order.dateModified
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public Date getDatemodified() {
		return datemodified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_prod_order.dateModified
	 * @param datemodified  the value for app_fd_ec_prod_order.dateModified
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_prod_order.c_amount
	 * @return  the value of app_fd_ec_prod_order.c_amount
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public String getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_prod_order.c_amount
	 * @param amount  the value for app_fd_ec_prod_order.c_amount
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void setAmount(String amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_prod_order.c_couponAmount
	 * @return  the value of app_fd_ec_prod_order.c_couponAmount
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public String getCouponAmount() {
		return couponAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_prod_order.c_couponAmount
	 * @param couponAmount  the value for app_fd_ec_prod_order.c_couponAmount
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void setCouponAmount(String couponAmount) {
		this.couponAmount = couponAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_prod_order.c_orderNo
	 * @return  the value of app_fd_ec_prod_order.c_orderNo
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public String getOrderNo() {
		return orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_prod_order.c_orderNo
	 * @param orderNo  the value for app_fd_ec_prod_order.c_orderNo
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_prod_order.c_usePoint
	 * @return  the value of app_fd_ec_prod_order.c_usePoint
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public String getUsePoint() {
		return usePoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_prod_order.c_usePoint
	 * @param usePoint  the value for app_fd_ec_prod_order.c_usePoint
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void setUsePoint(String usePoint) {
		this.usePoint = usePoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_prod_order.c_user_id
	 * @return  the value of app_fd_ec_prod_order.c_user_id
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_prod_order.c_user_id
	 * @param userId  the value for app_fd_ec_prod_order.c_user_id
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_prod_order.c_netAmount
	 * @return  the value of app_fd_ec_prod_order.c_netAmount
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public String getNetAmount() {
		return netAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_prod_order.c_netAmount
	 * @param netAmount  the value for app_fd_ec_prod_order.c_netAmount
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void setNetAmount(String netAmount) {
		this.netAmount = netAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_prod_order.c_paid
	 * @return  the value of app_fd_ec_prod_order.c_paid
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public String getPaid() {
		return paid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_prod_order.c_paid
	 * @param paid  the value for app_fd_ec_prod_order.c_paid
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void setPaid(String paid) {
		this.paid = paid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_prod_order.c_paymentTime
	 * @return  the value of app_fd_ec_prod_order.c_paymentTime
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public String getPaymentTime() {
		return paymentTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_prod_order.c_paymentTime
	 * @param paymentTime  the value for app_fd_ec_prod_order.c_paymentTime
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void setPaymentTime(String paymentTime) {
		this.paymentTime = paymentTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_prod_order.c_grouDiscount
	 * @return  the value of app_fd_ec_prod_order.c_grouDiscount
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public String getGrouDiscount() {
		return grouDiscount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_prod_order.c_grouDiscount
	 * @param grouDiscount  the value for app_fd_ec_prod_order.c_grouDiscount
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void setGrouDiscount(String grouDiscount) {
		this.grouDiscount = grouDiscount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_prod_order.c_address_id
	 * @return  the value of app_fd_ec_prod_order.c_address_id
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public String getAddressId() {
		return addressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_prod_order.c_address_id
	 * @param addressId  the value for app_fd_ec_prod_order.c_address_id
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void setAddressId(String addressId) {
		this.addressId = addressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_prod_order.c_productDiscount
	 * @return  the value of app_fd_ec_prod_order.c_productDiscount
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public String getProductDiscount() {
		return productDiscount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_prod_order.c_productDiscount
	 * @param productDiscount  the value for app_fd_ec_prod_order.c_productDiscount
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void setProductDiscount(String productDiscount) {
		this.productDiscount = productDiscount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_prod_order.c_channel
	 * @return  the value of app_fd_ec_prod_order.c_channel
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public String getChannel() {
		return channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_prod_order.c_channel
	 * @param channel  the value for app_fd_ec_prod_order.c_channel
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void setChannel(String channel) {
		this.channel = channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_prod_order.c_buyerMessage
	 * @return  the value of app_fd_ec_prod_order.c_buyerMessage
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public String getBuyerMessage() {
		return buyerMessage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_prod_order.c_buyerMessage
	 * @param buyerMessage  the value for app_fd_ec_prod_order.c_buyerMessage
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void setBuyerMessage(String buyerMessage) {
		this.buyerMessage = buyerMessage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_prod_order.c_outTradeNo
	 * @return  the value of app_fd_ec_prod_order.c_outTradeNo
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public String getOutTradeNo() {
		return outTradeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_prod_order.c_outTradeNo
	 * @param outTradeNo  the value for app_fd_ec_prod_order.c_outTradeNo
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void setOutTradeNo(String outTradeNo) {
		this.outTradeNo = outTradeNo;
	}

	public static final String CHANNEL_WX="wx";
	public static final String CHANNEL_ZFB="zfb";
	public static final String PAID_YES="1";
	public static final String PAID_NO="0";
	private int netAmountFen;
	private List<ProdOrderItem> orderItems;
	private List<Payment> payments;
	private String hasZeroAmountPay;

	public String getHasZeroAmountPay() {
		return hasZeroAmountPay;
	}

	public void setHasZeroAmountPay(String hasZeroAmountPay) {
		this.hasZeroAmountPay = hasZeroAmountPay;
	}

	public List<Payment> getPayments() {
		return payments;
	}

	public void setPayments(List<Payment> payments) {
		this.payments = payments;
	}

	public List<ProdOrderItem> getOrderItems() {
		return orderItems;
	}

	public void setOrderItems(List<ProdOrderItem> orderItems) {
		this.orderItems = orderItems;
	}

	public int getNetAmountFen() {
		return netAmountFen;
	}

	public void setNetAmountFen(int netAmountFen) {
		this.netAmountFen = netAmountFen;
	}
}