package com.wally.hiread.model.order;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProdOrderExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table app_fd_ec_prod_order
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table app_fd_ec_prod_order
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table app_fd_ec_prod_order
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_prod_order
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public ProdOrderExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_prod_order
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_prod_order
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_prod_order
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_prod_order
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_prod_order
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_prod_order
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_prod_order
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_prod_order
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_prod_order
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_prod_order
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table app_fd_ec_prod_order
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andDatecreatedIsNull() {
			addCriterion("dateCreated is null");
			return (Criteria) this;
		}

		public Criteria andDatecreatedIsNotNull() {
			addCriterion("dateCreated is not null");
			return (Criteria) this;
		}

		public Criteria andDatecreatedEqualTo(Date value) {
			addCriterion("dateCreated =", value, "datecreated");
			return (Criteria) this;
		}

		public Criteria andDatecreatedNotEqualTo(Date value) {
			addCriterion("dateCreated <>", value, "datecreated");
			return (Criteria) this;
		}

		public Criteria andDatecreatedGreaterThan(Date value) {
			addCriterion("dateCreated >", value, "datecreated");
			return (Criteria) this;
		}

		public Criteria andDatecreatedGreaterThanOrEqualTo(Date value) {
			addCriterion("dateCreated >=", value, "datecreated");
			return (Criteria) this;
		}

		public Criteria andDatecreatedLessThan(Date value) {
			addCriterion("dateCreated <", value, "datecreated");
			return (Criteria) this;
		}

		public Criteria andDatecreatedLessThanOrEqualTo(Date value) {
			addCriterion("dateCreated <=", value, "datecreated");
			return (Criteria) this;
		}

		public Criteria andDatecreatedIn(List<Date> values) {
			addCriterion("dateCreated in", values, "datecreated");
			return (Criteria) this;
		}

		public Criteria andDatecreatedNotIn(List<Date> values) {
			addCriterion("dateCreated not in", values, "datecreated");
			return (Criteria) this;
		}

		public Criteria andDatecreatedBetween(Date value1, Date value2) {
			addCriterion("dateCreated between", value1, value2, "datecreated");
			return (Criteria) this;
		}

		public Criteria andDatecreatedNotBetween(Date value1, Date value2) {
			addCriterion("dateCreated not between", value1, value2,
					"datecreated");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedIsNull() {
			addCriterion("dateModified is null");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedIsNotNull() {
			addCriterion("dateModified is not null");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedEqualTo(Date value) {
			addCriterion("dateModified =", value, "datemodified");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedNotEqualTo(Date value) {
			addCriterion("dateModified <>", value, "datemodified");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedGreaterThan(Date value) {
			addCriterion("dateModified >", value, "datemodified");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedGreaterThanOrEqualTo(Date value) {
			addCriterion("dateModified >=", value, "datemodified");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedLessThan(Date value) {
			addCriterion("dateModified <", value, "datemodified");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedLessThanOrEqualTo(Date value) {
			addCriterion("dateModified <=", value, "datemodified");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedIn(List<Date> values) {
			addCriterion("dateModified in", values, "datemodified");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedNotIn(List<Date> values) {
			addCriterion("dateModified not in", values, "datemodified");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedBetween(Date value1, Date value2) {
			addCriterion("dateModified between", value1, value2, "datemodified");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedNotBetween(Date value1, Date value2) {
			addCriterion("dateModified not between", value1, value2,
					"datemodified");
			return (Criteria) this;
		}

		public Criteria andAmountIsNull() {
			addCriterion("c_amount is null");
			return (Criteria) this;
		}

		public Criteria andAmountIsNotNull() {
			addCriterion("c_amount is not null");
			return (Criteria) this;
		}

		public Criteria andAmountEqualTo(String value) {
			addCriterion("c_amount =", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotEqualTo(String value) {
			addCriterion("c_amount <>", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThan(String value) {
			addCriterion("c_amount >", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThanOrEqualTo(String value) {
			addCriterion("c_amount >=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThan(String value) {
			addCriterion("c_amount <", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThanOrEqualTo(String value) {
			addCriterion("c_amount <=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLike(String value) {
			addCriterion("c_amount like", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotLike(String value) {
			addCriterion("c_amount not like", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountIn(List<String> values) {
			addCriterion("c_amount in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotIn(List<String> values) {
			addCriterion("c_amount not in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountBetween(String value1, String value2) {
			addCriterion("c_amount between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotBetween(String value1, String value2) {
			addCriterion("c_amount not between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andCouponAmountIsNull() {
			addCriterion("c_couponAmount is null");
			return (Criteria) this;
		}

		public Criteria andCouponAmountIsNotNull() {
			addCriterion("c_couponAmount is not null");
			return (Criteria) this;
		}

		public Criteria andCouponAmountEqualTo(String value) {
			addCriterion("c_couponAmount =", value, "couponAmount");
			return (Criteria) this;
		}

		public Criteria andCouponAmountNotEqualTo(String value) {
			addCriterion("c_couponAmount <>", value, "couponAmount");
			return (Criteria) this;
		}

		public Criteria andCouponAmountGreaterThan(String value) {
			addCriterion("c_couponAmount >", value, "couponAmount");
			return (Criteria) this;
		}

		public Criteria andCouponAmountGreaterThanOrEqualTo(String value) {
			addCriterion("c_couponAmount >=", value, "couponAmount");
			return (Criteria) this;
		}

		public Criteria andCouponAmountLessThan(String value) {
			addCriterion("c_couponAmount <", value, "couponAmount");
			return (Criteria) this;
		}

		public Criteria andCouponAmountLessThanOrEqualTo(String value) {
			addCriterion("c_couponAmount <=", value, "couponAmount");
			return (Criteria) this;
		}

		public Criteria andCouponAmountLike(String value) {
			addCriterion("c_couponAmount like", value, "couponAmount");
			return (Criteria) this;
		}

		public Criteria andCouponAmountNotLike(String value) {
			addCriterion("c_couponAmount not like", value, "couponAmount");
			return (Criteria) this;
		}

		public Criteria andCouponAmountIn(List<String> values) {
			addCriterion("c_couponAmount in", values, "couponAmount");
			return (Criteria) this;
		}

		public Criteria andCouponAmountNotIn(List<String> values) {
			addCriterion("c_couponAmount not in", values, "couponAmount");
			return (Criteria) this;
		}

		public Criteria andCouponAmountBetween(String value1, String value2) {
			addCriterion("c_couponAmount between", value1, value2,
					"couponAmount");
			return (Criteria) this;
		}

		public Criteria andCouponAmountNotBetween(String value1, String value2) {
			addCriterion("c_couponAmount not between", value1, value2,
					"couponAmount");
			return (Criteria) this;
		}

		public Criteria andOrderNoIsNull() {
			addCriterion("c_orderNo is null");
			return (Criteria) this;
		}

		public Criteria andOrderNoIsNotNull() {
			addCriterion("c_orderNo is not null");
			return (Criteria) this;
		}

		public Criteria andOrderNoEqualTo(String value) {
			addCriterion("c_orderNo =", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotEqualTo(String value) {
			addCriterion("c_orderNo <>", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoGreaterThan(String value) {
			addCriterion("c_orderNo >", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
			addCriterion("c_orderNo >=", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoLessThan(String value) {
			addCriterion("c_orderNo <", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoLessThanOrEqualTo(String value) {
			addCriterion("c_orderNo <=", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoLike(String value) {
			addCriterion("c_orderNo like", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotLike(String value) {
			addCriterion("c_orderNo not like", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoIn(List<String> values) {
			addCriterion("c_orderNo in", values, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotIn(List<String> values) {
			addCriterion("c_orderNo not in", values, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoBetween(String value1, String value2) {
			addCriterion("c_orderNo between", value1, value2, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotBetween(String value1, String value2) {
			addCriterion("c_orderNo not between", value1, value2, "orderNo");
			return (Criteria) this;
		}

		public Criteria andUsePointIsNull() {
			addCriterion("c_usePoint is null");
			return (Criteria) this;
		}

		public Criteria andUsePointIsNotNull() {
			addCriterion("c_usePoint is not null");
			return (Criteria) this;
		}

		public Criteria andUsePointEqualTo(String value) {
			addCriterion("c_usePoint =", value, "usePoint");
			return (Criteria) this;
		}

		public Criteria andUsePointNotEqualTo(String value) {
			addCriterion("c_usePoint <>", value, "usePoint");
			return (Criteria) this;
		}

		public Criteria andUsePointGreaterThan(String value) {
			addCriterion("c_usePoint >", value, "usePoint");
			return (Criteria) this;
		}

		public Criteria andUsePointGreaterThanOrEqualTo(String value) {
			addCriterion("c_usePoint >=", value, "usePoint");
			return (Criteria) this;
		}

		public Criteria andUsePointLessThan(String value) {
			addCriterion("c_usePoint <", value, "usePoint");
			return (Criteria) this;
		}

		public Criteria andUsePointLessThanOrEqualTo(String value) {
			addCriterion("c_usePoint <=", value, "usePoint");
			return (Criteria) this;
		}

		public Criteria andUsePointLike(String value) {
			addCriterion("c_usePoint like", value, "usePoint");
			return (Criteria) this;
		}

		public Criteria andUsePointNotLike(String value) {
			addCriterion("c_usePoint not like", value, "usePoint");
			return (Criteria) this;
		}

		public Criteria andUsePointIn(List<String> values) {
			addCriterion("c_usePoint in", values, "usePoint");
			return (Criteria) this;
		}

		public Criteria andUsePointNotIn(List<String> values) {
			addCriterion("c_usePoint not in", values, "usePoint");
			return (Criteria) this;
		}

		public Criteria andUsePointBetween(String value1, String value2) {
			addCriterion("c_usePoint between", value1, value2, "usePoint");
			return (Criteria) this;
		}

		public Criteria andUsePointNotBetween(String value1, String value2) {
			addCriterion("c_usePoint not between", value1, value2, "usePoint");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("c_user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("c_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("c_user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("c_user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("c_user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("c_user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("c_user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("c_user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("c_user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("c_user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("c_user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("c_user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("c_user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("c_user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andNetAmountIsNull() {
			addCriterion("c_netAmount is null");
			return (Criteria) this;
		}

		public Criteria andNetAmountIsNotNull() {
			addCriterion("c_netAmount is not null");
			return (Criteria) this;
		}

		public Criteria andNetAmountEqualTo(String value) {
			addCriterion("c_netAmount =", value, "netAmount");
			return (Criteria) this;
		}

		public Criteria andNetAmountNotEqualTo(String value) {
			addCriterion("c_netAmount <>", value, "netAmount");
			return (Criteria) this;
		}

		public Criteria andNetAmountGreaterThan(String value) {
			addCriterion("c_netAmount >", value, "netAmount");
			return (Criteria) this;
		}

		public Criteria andNetAmountGreaterThanOrEqualTo(String value) {
			addCriterion("c_netAmount >=", value, "netAmount");
			return (Criteria) this;
		}

		public Criteria andNetAmountLessThan(String value) {
			addCriterion("c_netAmount <", value, "netAmount");
			return (Criteria) this;
		}

		public Criteria andNetAmountLessThanOrEqualTo(String value) {
			addCriterion("c_netAmount <=", value, "netAmount");
			return (Criteria) this;
		}

		public Criteria andNetAmountLike(String value) {
			addCriterion("c_netAmount like", value, "netAmount");
			return (Criteria) this;
		}

		public Criteria andNetAmountNotLike(String value) {
			addCriterion("c_netAmount not like", value, "netAmount");
			return (Criteria) this;
		}

		public Criteria andNetAmountIn(List<String> values) {
			addCriterion("c_netAmount in", values, "netAmount");
			return (Criteria) this;
		}

		public Criteria andNetAmountNotIn(List<String> values) {
			addCriterion("c_netAmount not in", values, "netAmount");
			return (Criteria) this;
		}

		public Criteria andNetAmountBetween(String value1, String value2) {
			addCriterion("c_netAmount between", value1, value2, "netAmount");
			return (Criteria) this;
		}

		public Criteria andNetAmountNotBetween(String value1, String value2) {
			addCriterion("c_netAmount not between", value1, value2, "netAmount");
			return (Criteria) this;
		}

		public Criteria andPaidIsNull() {
			addCriterion("c_paid is null");
			return (Criteria) this;
		}

		public Criteria andPaidIsNotNull() {
			addCriterion("c_paid is not null");
			return (Criteria) this;
		}

		public Criteria andPaidEqualTo(String value) {
			addCriterion("c_paid =", value, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidNotEqualTo(String value) {
			addCriterion("c_paid <>", value, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidGreaterThan(String value) {
			addCriterion("c_paid >", value, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidGreaterThanOrEqualTo(String value) {
			addCriterion("c_paid >=", value, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidLessThan(String value) {
			addCriterion("c_paid <", value, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidLessThanOrEqualTo(String value) {
			addCriterion("c_paid <=", value, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidLike(String value) {
			addCriterion("c_paid like", value, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidNotLike(String value) {
			addCriterion("c_paid not like", value, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidIn(List<String> values) {
			addCriterion("c_paid in", values, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidNotIn(List<String> values) {
			addCriterion("c_paid not in", values, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidBetween(String value1, String value2) {
			addCriterion("c_paid between", value1, value2, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidNotBetween(String value1, String value2) {
			addCriterion("c_paid not between", value1, value2, "paid");
			return (Criteria) this;
		}

		public Criteria andPaymentTimeIsNull() {
			addCriterion("c_paymentTime is null");
			return (Criteria) this;
		}

		public Criteria andPaymentTimeIsNotNull() {
			addCriterion("c_paymentTime is not null");
			return (Criteria) this;
		}

		public Criteria andPaymentTimeEqualTo(String value) {
			addCriterion("c_paymentTime =", value, "paymentTime");
			return (Criteria) this;
		}

		public Criteria andPaymentTimeNotEqualTo(String value) {
			addCriterion("c_paymentTime <>", value, "paymentTime");
			return (Criteria) this;
		}

		public Criteria andPaymentTimeGreaterThan(String value) {
			addCriterion("c_paymentTime >", value, "paymentTime");
			return (Criteria) this;
		}

		public Criteria andPaymentTimeGreaterThanOrEqualTo(String value) {
			addCriterion("c_paymentTime >=", value, "paymentTime");
			return (Criteria) this;
		}

		public Criteria andPaymentTimeLessThan(String value) {
			addCriterion("c_paymentTime <", value, "paymentTime");
			return (Criteria) this;
		}

		public Criteria andPaymentTimeLessThanOrEqualTo(String value) {
			addCriterion("c_paymentTime <=", value, "paymentTime");
			return (Criteria) this;
		}

		public Criteria andPaymentTimeLike(String value) {
			addCriterion("c_paymentTime like", value, "paymentTime");
			return (Criteria) this;
		}

		public Criteria andPaymentTimeNotLike(String value) {
			addCriterion("c_paymentTime not like", value, "paymentTime");
			return (Criteria) this;
		}

		public Criteria andPaymentTimeIn(List<String> values) {
			addCriterion("c_paymentTime in", values, "paymentTime");
			return (Criteria) this;
		}

		public Criteria andPaymentTimeNotIn(List<String> values) {
			addCriterion("c_paymentTime not in", values, "paymentTime");
			return (Criteria) this;
		}

		public Criteria andPaymentTimeBetween(String value1, String value2) {
			addCriterion("c_paymentTime between", value1, value2, "paymentTime");
			return (Criteria) this;
		}

		public Criteria andPaymentTimeNotBetween(String value1, String value2) {
			addCriterion("c_paymentTime not between", value1, value2,
					"paymentTime");
			return (Criteria) this;
		}

		public Criteria andGrouDiscountIsNull() {
			addCriterion("c_grouDiscount is null");
			return (Criteria) this;
		}

		public Criteria andGrouDiscountIsNotNull() {
			addCriterion("c_grouDiscount is not null");
			return (Criteria) this;
		}

		public Criteria andGrouDiscountEqualTo(String value) {
			addCriterion("c_grouDiscount =", value, "grouDiscount");
			return (Criteria) this;
		}

		public Criteria andGrouDiscountNotEqualTo(String value) {
			addCriterion("c_grouDiscount <>", value, "grouDiscount");
			return (Criteria) this;
		}

		public Criteria andGrouDiscountGreaterThan(String value) {
			addCriterion("c_grouDiscount >", value, "grouDiscount");
			return (Criteria) this;
		}

		public Criteria andGrouDiscountGreaterThanOrEqualTo(String value) {
			addCriterion("c_grouDiscount >=", value, "grouDiscount");
			return (Criteria) this;
		}

		public Criteria andGrouDiscountLessThan(String value) {
			addCriterion("c_grouDiscount <", value, "grouDiscount");
			return (Criteria) this;
		}

		public Criteria andGrouDiscountLessThanOrEqualTo(String value) {
			addCriterion("c_grouDiscount <=", value, "grouDiscount");
			return (Criteria) this;
		}

		public Criteria andGrouDiscountLike(String value) {
			addCriterion("c_grouDiscount like", value, "grouDiscount");
			return (Criteria) this;
		}

		public Criteria andGrouDiscountNotLike(String value) {
			addCriterion("c_grouDiscount not like", value, "grouDiscount");
			return (Criteria) this;
		}

		public Criteria andGrouDiscountIn(List<String> values) {
			addCriterion("c_grouDiscount in", values, "grouDiscount");
			return (Criteria) this;
		}

		public Criteria andGrouDiscountNotIn(List<String> values) {
			addCriterion("c_grouDiscount not in", values, "grouDiscount");
			return (Criteria) this;
		}

		public Criteria andGrouDiscountBetween(String value1, String value2) {
			addCriterion("c_grouDiscount between", value1, value2,
					"grouDiscount");
			return (Criteria) this;
		}

		public Criteria andGrouDiscountNotBetween(String value1, String value2) {
			addCriterion("c_grouDiscount not between", value1, value2,
					"grouDiscount");
			return (Criteria) this;
		}

		public Criteria andAddressIdIsNull() {
			addCriterion("c_address_id is null");
			return (Criteria) this;
		}

		public Criteria andAddressIdIsNotNull() {
			addCriterion("c_address_id is not null");
			return (Criteria) this;
		}

		public Criteria andAddressIdEqualTo(String value) {
			addCriterion("c_address_id =", value, "addressId");
			return (Criteria) this;
		}

		public Criteria andAddressIdNotEqualTo(String value) {
			addCriterion("c_address_id <>", value, "addressId");
			return (Criteria) this;
		}

		public Criteria andAddressIdGreaterThan(String value) {
			addCriterion("c_address_id >", value, "addressId");
			return (Criteria) this;
		}

		public Criteria andAddressIdGreaterThanOrEqualTo(String value) {
			addCriterion("c_address_id >=", value, "addressId");
			return (Criteria) this;
		}

		public Criteria andAddressIdLessThan(String value) {
			addCriterion("c_address_id <", value, "addressId");
			return (Criteria) this;
		}

		public Criteria andAddressIdLessThanOrEqualTo(String value) {
			addCriterion("c_address_id <=", value, "addressId");
			return (Criteria) this;
		}

		public Criteria andAddressIdLike(String value) {
			addCriterion("c_address_id like", value, "addressId");
			return (Criteria) this;
		}

		public Criteria andAddressIdNotLike(String value) {
			addCriterion("c_address_id not like", value, "addressId");
			return (Criteria) this;
		}

		public Criteria andAddressIdIn(List<String> values) {
			addCriterion("c_address_id in", values, "addressId");
			return (Criteria) this;
		}

		public Criteria andAddressIdNotIn(List<String> values) {
			addCriterion("c_address_id not in", values, "addressId");
			return (Criteria) this;
		}

		public Criteria andAddressIdBetween(String value1, String value2) {
			addCriterion("c_address_id between", value1, value2, "addressId");
			return (Criteria) this;
		}

		public Criteria andAddressIdNotBetween(String value1, String value2) {
			addCriterion("c_address_id not between", value1, value2,
					"addressId");
			return (Criteria) this;
		}

		public Criteria andProductDiscountIsNull() {
			addCriterion("c_productDiscount is null");
			return (Criteria) this;
		}

		public Criteria andProductDiscountIsNotNull() {
			addCriterion("c_productDiscount is not null");
			return (Criteria) this;
		}

		public Criteria andProductDiscountEqualTo(String value) {
			addCriterion("c_productDiscount =", value, "productDiscount");
			return (Criteria) this;
		}

		public Criteria andProductDiscountNotEqualTo(String value) {
			addCriterion("c_productDiscount <>", value, "productDiscount");
			return (Criteria) this;
		}

		public Criteria andProductDiscountGreaterThan(String value) {
			addCriterion("c_productDiscount >", value, "productDiscount");
			return (Criteria) this;
		}

		public Criteria andProductDiscountGreaterThanOrEqualTo(String value) {
			addCriterion("c_productDiscount >=", value, "productDiscount");
			return (Criteria) this;
		}

		public Criteria andProductDiscountLessThan(String value) {
			addCriterion("c_productDiscount <", value, "productDiscount");
			return (Criteria) this;
		}

		public Criteria andProductDiscountLessThanOrEqualTo(String value) {
			addCriterion("c_productDiscount <=", value, "productDiscount");
			return (Criteria) this;
		}

		public Criteria andProductDiscountLike(String value) {
			addCriterion("c_productDiscount like", value, "productDiscount");
			return (Criteria) this;
		}

		public Criteria andProductDiscountNotLike(String value) {
			addCriterion("c_productDiscount not like", value, "productDiscount");
			return (Criteria) this;
		}

		public Criteria andProductDiscountIn(List<String> values) {
			addCriterion("c_productDiscount in", values, "productDiscount");
			return (Criteria) this;
		}

		public Criteria andProductDiscountNotIn(List<String> values) {
			addCriterion("c_productDiscount not in", values, "productDiscount");
			return (Criteria) this;
		}

		public Criteria andProductDiscountBetween(String value1, String value2) {
			addCriterion("c_productDiscount between", value1, value2,
					"productDiscount");
			return (Criteria) this;
		}

		public Criteria andProductDiscountNotBetween(String value1,
				String value2) {
			addCriterion("c_productDiscount not between", value1, value2,
					"productDiscount");
			return (Criteria) this;
		}

		public Criteria andChannelIsNull() {
			addCriterion("c_channel is null");
			return (Criteria) this;
		}

		public Criteria andChannelIsNotNull() {
			addCriterion("c_channel is not null");
			return (Criteria) this;
		}

		public Criteria andChannelEqualTo(String value) {
			addCriterion("c_channel =", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNotEqualTo(String value) {
			addCriterion("c_channel <>", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelGreaterThan(String value) {
			addCriterion("c_channel >", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelGreaterThanOrEqualTo(String value) {
			addCriterion("c_channel >=", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelLessThan(String value) {
			addCriterion("c_channel <", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelLessThanOrEqualTo(String value) {
			addCriterion("c_channel <=", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelLike(String value) {
			addCriterion("c_channel like", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNotLike(String value) {
			addCriterion("c_channel not like", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelIn(List<String> values) {
			addCriterion("c_channel in", values, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNotIn(List<String> values) {
			addCriterion("c_channel not in", values, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelBetween(String value1, String value2) {
			addCriterion("c_channel between", value1, value2, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNotBetween(String value1, String value2) {
			addCriterion("c_channel not between", value1, value2, "channel");
			return (Criteria) this;
		}

		public Criteria andBuyerMessageIsNull() {
			addCriterion("c_buyerMessage is null");
			return (Criteria) this;
		}

		public Criteria andBuyerMessageIsNotNull() {
			addCriterion("c_buyerMessage is not null");
			return (Criteria) this;
		}

		public Criteria andBuyerMessageEqualTo(String value) {
			addCriterion("c_buyerMessage =", value, "buyerMessage");
			return (Criteria) this;
		}

		public Criteria andBuyerMessageNotEqualTo(String value) {
			addCriterion("c_buyerMessage <>", value, "buyerMessage");
			return (Criteria) this;
		}

		public Criteria andBuyerMessageGreaterThan(String value) {
			addCriterion("c_buyerMessage >", value, "buyerMessage");
			return (Criteria) this;
		}

		public Criteria andBuyerMessageGreaterThanOrEqualTo(String value) {
			addCriterion("c_buyerMessage >=", value, "buyerMessage");
			return (Criteria) this;
		}

		public Criteria andBuyerMessageLessThan(String value) {
			addCriterion("c_buyerMessage <", value, "buyerMessage");
			return (Criteria) this;
		}

		public Criteria andBuyerMessageLessThanOrEqualTo(String value) {
			addCriterion("c_buyerMessage <=", value, "buyerMessage");
			return (Criteria) this;
		}

		public Criteria andBuyerMessageLike(String value) {
			addCriterion("c_buyerMessage like", value, "buyerMessage");
			return (Criteria) this;
		}

		public Criteria andBuyerMessageNotLike(String value) {
			addCriterion("c_buyerMessage not like", value, "buyerMessage");
			return (Criteria) this;
		}

		public Criteria andBuyerMessageIn(List<String> values) {
			addCriterion("c_buyerMessage in", values, "buyerMessage");
			return (Criteria) this;
		}

		public Criteria andBuyerMessageNotIn(List<String> values) {
			addCriterion("c_buyerMessage not in", values, "buyerMessage");
			return (Criteria) this;
		}

		public Criteria andBuyerMessageBetween(String value1, String value2) {
			addCriterion("c_buyerMessage between", value1, value2,
					"buyerMessage");
			return (Criteria) this;
		}

		public Criteria andBuyerMessageNotBetween(String value1, String value2) {
			addCriterion("c_buyerMessage not between", value1, value2,
					"buyerMessage");
			return (Criteria) this;
		}

		public Criteria andOutTradeNoIsNull() {
			addCriterion("c_outTradeNo is null");
			return (Criteria) this;
		}

		public Criteria andOutTradeNoIsNotNull() {
			addCriterion("c_outTradeNo is not null");
			return (Criteria) this;
		}

		public Criteria andOutTradeNoEqualTo(String value) {
			addCriterion("c_outTradeNo =", value, "outTradeNo");
			return (Criteria) this;
		}

		public Criteria andOutTradeNoNotEqualTo(String value) {
			addCriterion("c_outTradeNo <>", value, "outTradeNo");
			return (Criteria) this;
		}

		public Criteria andOutTradeNoGreaterThan(String value) {
			addCriterion("c_outTradeNo >", value, "outTradeNo");
			return (Criteria) this;
		}

		public Criteria andOutTradeNoGreaterThanOrEqualTo(String value) {
			addCriterion("c_outTradeNo >=", value, "outTradeNo");
			return (Criteria) this;
		}

		public Criteria andOutTradeNoLessThan(String value) {
			addCriterion("c_outTradeNo <", value, "outTradeNo");
			return (Criteria) this;
		}

		public Criteria andOutTradeNoLessThanOrEqualTo(String value) {
			addCriterion("c_outTradeNo <=", value, "outTradeNo");
			return (Criteria) this;
		}

		public Criteria andOutTradeNoLike(String value) {
			addCriterion("c_outTradeNo like", value, "outTradeNo");
			return (Criteria) this;
		}

		public Criteria andOutTradeNoNotLike(String value) {
			addCriterion("c_outTradeNo not like", value, "outTradeNo");
			return (Criteria) this;
		}

		public Criteria andOutTradeNoIn(List<String> values) {
			addCriterion("c_outTradeNo in", values, "outTradeNo");
			return (Criteria) this;
		}

		public Criteria andOutTradeNoNotIn(List<String> values) {
			addCriterion("c_outTradeNo not in", values, "outTradeNo");
			return (Criteria) this;
		}

		public Criteria andOutTradeNoBetween(String value1, String value2) {
			addCriterion("c_outTradeNo between", value1, value2, "outTradeNo");
			return (Criteria) this;
		}

		public Criteria andOutTradeNoNotBetween(String value1, String value2) {
			addCriterion("c_outTradeNo not between", value1, value2,
					"outTradeNo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table app_fd_ec_prod_order
	 * @mbggenerated  Thu Jun 22 10:12:21 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_fd_ec_prod_order
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 08 13:51:37 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}