package com.wally.hiread.dao.sys;

import com.wally.hiread.model.sys.Testing;
import com.wally.hiread.model.sys.TestingExample;
import java.util.List;

public interface TestingMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_testing
	 * @mbggenerated  Thu Aug 31 14:03:15 CST 2017
	 */
	int countByExample(TestingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_testing
	 * @mbggenerated  Thu Aug 31 14:03:15 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_testing
	 * @mbggenerated  Thu Aug 31 14:03:15 CST 2017
	 */
	int insert(Testing record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_testing
	 * @mbggenerated  Thu Aug 31 14:03:15 CST 2017
	 */
	int insertSelective(Testing record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_testing
	 * @mbggenerated  Thu Aug 31 14:03:15 CST 2017
	 */
	List<Testing> selectByExample(TestingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_testing
	 * @mbggenerated  Thu Aug 31 14:03:15 CST 2017
	 */
	Testing selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_testing
	 * @mbggenerated  Thu Aug 31 14:03:15 CST 2017
	 */
	int updateByPrimaryKeySelective(Testing record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_testing
	 * @mbggenerated  Thu Aug 31 14:03:15 CST 2017
	 */
	int updateByPrimaryKey(Testing record);
}