package com.wally.hiread.dao.order;

import com.wally.hiread.model.order.AgentRequest;
import com.wally.hiread.model.order.AgentRequestExample;
import java.util.List;

public interface AgentRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_agent_request
     *
     * @mbggenerated Tue Aug 01 09:55:11 CST 2017
     */
    int countByExample(AgentRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_agent_request
     *
     * @mbggenerated Tue Aug 01 09:55:11 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_agent_request
     *
     * @mbggenerated Tue Aug 01 09:55:11 CST 2017
     */
    int insert(AgentRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_agent_request
     *
     * @mbggenerated Tue Aug 01 09:55:11 CST 2017
     */
    int insertSelective(AgentRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_agent_request
     *
     * @mbggenerated Tue Aug 01 09:55:11 CST 2017
     */
    List<AgentRequest> selectByExample(AgentRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_agent_request
     *
     * @mbggenerated Tue Aug 01 09:55:11 CST 2017
     */
    AgentRequest selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_agent_request
     *
     * @mbggenerated Tue Aug 01 09:55:11 CST 2017
     */
    int updateByPrimaryKeySelective(AgentRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_agent_request
     *
     * @mbggenerated Tue Aug 01 09:55:11 CST 2017
     */
    int updateByPrimaryKey(AgentRequest record);
}