package com.wally.hiread.dao.order;

import com.wally.hiread.model.order.Campain;
import com.wally.hiread.model.order.CampainExample;
import java.util.List;

public interface CampainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_campain
     *
     * @mbggenerated Thu Jun 22 09:41:38 CST 2017
     */
    int countByExample(CampainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_campain
     *
     * @mbggenerated Thu Jun 22 09:41:38 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_campain
     *
     * @mbggenerated Thu Jun 22 09:41:38 CST 2017
     */
    int insert(Campain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_campain
     *
     * @mbggenerated Thu Jun 22 09:41:38 CST 2017
     */
    int insertSelective(Campain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_campain
     *
     * @mbggenerated Thu Jun 22 09:41:38 CST 2017
     */
    List<Campain> selectByExample(CampainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_campain
     *
     * @mbggenerated Thu Jun 22 09:41:38 CST 2017
     */
    Campain selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_campain
     *
     * @mbggenerated Thu Jun 22 09:41:38 CST 2017
     */
    int updateByPrimaryKeySelective(Campain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_campain
     *
     * @mbggenerated Thu Jun 22 09:41:38 CST 2017
     */
    int updateByPrimaryKey(Campain record);
}