package com.wally.hiread.model.product;

import java.util.Date;

public class PractiseOpt {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_practise_opt.id
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_practise_opt.dateCreated
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	private Date datecreated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_practise_opt.dateModified
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	private Date datemodified;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_practise_opt.c_optionType
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	private String optionType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_practise_opt.c_pair1
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	private String pair1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_practise_opt.c_pair2Audio
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	private String pair2Audio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_practise_opt.c_pair1Type
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	private String pair1Type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_practise_opt.c_pair2Type
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	private String pair2Type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_practise_opt.c_correct
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	private String correct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_practise_opt.c_pair1Audio
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	private String pair1Audio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_practise_opt.c_practise_id
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	private String practiseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_practise_opt.c_sort
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	private String sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_practise_opt.c_option
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	private String option;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_practise_opt.c_pair2
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	private String pair2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_practise_opt.c_optionImg
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	private String optionImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_practise_opt.c_pair2Img
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	private String pair2Img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_practise_opt.c_pair1Img
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	private String pair1Img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_practise_opt.c_isBlank
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	private String isBlank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_practise_opt.c_displayNum
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	private String displayNum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_practise_opt.id
	 * @return  the value of app_fd_ec_practise_opt.id
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_practise_opt.id
	 * @param id  the value for app_fd_ec_practise_opt.id
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_practise_opt.dateCreated
	 * @return  the value of app_fd_ec_practise_opt.dateCreated
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public Date getDatecreated() {
		return datecreated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_practise_opt.dateCreated
	 * @param datecreated  the value for app_fd_ec_practise_opt.dateCreated
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_practise_opt.dateModified
	 * @return  the value of app_fd_ec_practise_opt.dateModified
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public Date getDatemodified() {
		return datemodified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_practise_opt.dateModified
	 * @param datemodified  the value for app_fd_ec_practise_opt.dateModified
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_practise_opt.c_optionType
	 * @return  the value of app_fd_ec_practise_opt.c_optionType
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public String getOptionType() {
		return optionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_practise_opt.c_optionType
	 * @param optionType  the value for app_fd_ec_practise_opt.c_optionType
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public void setOptionType(String optionType) {
		this.optionType = optionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_practise_opt.c_pair1
	 * @return  the value of app_fd_ec_practise_opt.c_pair1
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public String getPair1() {
		return pair1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_practise_opt.c_pair1
	 * @param pair1  the value for app_fd_ec_practise_opt.c_pair1
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public void setPair1(String pair1) {
		this.pair1 = pair1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_practise_opt.c_pair2Audio
	 * @return  the value of app_fd_ec_practise_opt.c_pair2Audio
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public String getPair2Audio() {
		return pair2Audio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_practise_opt.c_pair2Audio
	 * @param pair2Audio  the value for app_fd_ec_practise_opt.c_pair2Audio
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public void setPair2Audio(String pair2Audio) {
		this.pair2Audio = pair2Audio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_practise_opt.c_pair1Type
	 * @return  the value of app_fd_ec_practise_opt.c_pair1Type
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public String getPair1Type() {
		return pair1Type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_practise_opt.c_pair1Type
	 * @param pair1Type  the value for app_fd_ec_practise_opt.c_pair1Type
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public void setPair1Type(String pair1Type) {
		this.pair1Type = pair1Type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_practise_opt.c_pair2Type
	 * @return  the value of app_fd_ec_practise_opt.c_pair2Type
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public String getPair2Type() {
		return pair2Type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_practise_opt.c_pair2Type
	 * @param pair2Type  the value for app_fd_ec_practise_opt.c_pair2Type
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public void setPair2Type(String pair2Type) {
		this.pair2Type = pair2Type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_practise_opt.c_correct
	 * @return  the value of app_fd_ec_practise_opt.c_correct
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public String getCorrect() {
		return correct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_practise_opt.c_correct
	 * @param correct  the value for app_fd_ec_practise_opt.c_correct
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public void setCorrect(String correct) {
		this.correct = correct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_practise_opt.c_pair1Audio
	 * @return  the value of app_fd_ec_practise_opt.c_pair1Audio
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public String getPair1Audio() {
		return pair1Audio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_practise_opt.c_pair1Audio
	 * @param pair1Audio  the value for app_fd_ec_practise_opt.c_pair1Audio
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public void setPair1Audio(String pair1Audio) {
		this.pair1Audio = pair1Audio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_practise_opt.c_practise_id
	 * @return  the value of app_fd_ec_practise_opt.c_practise_id
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public String getPractiseId() {
		return practiseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_practise_opt.c_practise_id
	 * @param practiseId  the value for app_fd_ec_practise_opt.c_practise_id
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public void setPractiseId(String practiseId) {
		this.practiseId = practiseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_practise_opt.c_sort
	 * @return  the value of app_fd_ec_practise_opt.c_sort
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public String getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_practise_opt.c_sort
	 * @param sort  the value for app_fd_ec_practise_opt.c_sort
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public void setSort(String sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_practise_opt.c_option
	 * @return  the value of app_fd_ec_practise_opt.c_option
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public String getOption() {
		return option;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_practise_opt.c_option
	 * @param option  the value for app_fd_ec_practise_opt.c_option
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public void setOption(String option) {
		this.option = option;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_practise_opt.c_pair2
	 * @return  the value of app_fd_ec_practise_opt.c_pair2
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public String getPair2() {
		return pair2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_practise_opt.c_pair2
	 * @param pair2  the value for app_fd_ec_practise_opt.c_pair2
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public void setPair2(String pair2) {
		this.pair2 = pair2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_practise_opt.c_optionImg
	 * @return  the value of app_fd_ec_practise_opt.c_optionImg
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public String getOptionImg() {
		return optionImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_practise_opt.c_optionImg
	 * @param optionImg  the value for app_fd_ec_practise_opt.c_optionImg
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public void setOptionImg(String optionImg) {
		this.optionImg = optionImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_practise_opt.c_pair2Img
	 * @return  the value of app_fd_ec_practise_opt.c_pair2Img
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public String getPair2Img() {
		return pair2Img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_practise_opt.c_pair2Img
	 * @param pair2Img  the value for app_fd_ec_practise_opt.c_pair2Img
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public void setPair2Img(String pair2Img) {
		this.pair2Img = pair2Img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_practise_opt.c_pair1Img
	 * @return  the value of app_fd_ec_practise_opt.c_pair1Img
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public String getPair1Img() {
		return pair1Img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_practise_opt.c_pair1Img
	 * @param pair1Img  the value for app_fd_ec_practise_opt.c_pair1Img
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public void setPair1Img(String pair1Img) {
		this.pair1Img = pair1Img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_practise_opt.c_isBlank
	 * @return  the value of app_fd_ec_practise_opt.c_isBlank
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public String getIsBlank() {
		return isBlank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_practise_opt.c_isBlank
	 * @param isBlank  the value for app_fd_ec_practise_opt.c_isBlank
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public void setIsBlank(String isBlank) {
		this.isBlank = isBlank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_practise_opt.c_displayNum
	 * @return  the value of app_fd_ec_practise_opt.c_displayNum
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public String getDisplayNum() {
		return displayNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_practise_opt.c_displayNum
	 * @param displayNum  the value for app_fd_ec_practise_opt.c_displayNum
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	public void setDisplayNum(String displayNum) {
		this.displayNum = displayNum;
	}

	public static final String TABLE_NAME="ec_practise_opt";
}