package com.wally.hiread.model.product;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table app_fd_ec_product
	 * @mbggenerated  Fri Jul 07 11:49:28 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table app_fd_ec_product
	 * @mbggenerated  Fri Jul 07 11:49:28 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table app_fd_ec_product
	 * @mbggenerated  Fri Jul 07 11:49:28 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_product
	 * @mbggenerated  Fri Jul 07 11:49:28 CST 2017
	 */
	public ProductExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_product
	 * @mbggenerated  Fri Jul 07 11:49:28 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_product
	 * @mbggenerated  Fri Jul 07 11:49:28 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_product
	 * @mbggenerated  Fri Jul 07 11:49:28 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_product
	 * @mbggenerated  Fri Jul 07 11:49:28 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_product
	 * @mbggenerated  Fri Jul 07 11:49:28 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_product
	 * @mbggenerated  Fri Jul 07 11:49:28 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_product
	 * @mbggenerated  Fri Jul 07 11:49:28 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_product
	 * @mbggenerated  Fri Jul 07 11:49:28 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_product
	 * @mbggenerated  Fri Jul 07 11:49:28 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_product
	 * @mbggenerated  Fri Jul 07 11:49:28 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table app_fd_ec_product
	 * @mbggenerated  Fri Jul 07 11:49:28 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andDatecreatedIsNull() {
			addCriterion("dateCreated is null");
			return (Criteria) this;
		}

		public Criteria andDatecreatedIsNotNull() {
			addCriterion("dateCreated is not null");
			return (Criteria) this;
		}

		public Criteria andDatecreatedEqualTo(Date value) {
			addCriterion("dateCreated =", value, "datecreated");
			return (Criteria) this;
		}

		public Criteria andDatecreatedNotEqualTo(Date value) {
			addCriterion("dateCreated <>", value, "datecreated");
			return (Criteria) this;
		}

		public Criteria andDatecreatedGreaterThan(Date value) {
			addCriterion("dateCreated >", value, "datecreated");
			return (Criteria) this;
		}

		public Criteria andDatecreatedGreaterThanOrEqualTo(Date value) {
			addCriterion("dateCreated >=", value, "datecreated");
			return (Criteria) this;
		}

		public Criteria andDatecreatedLessThan(Date value) {
			addCriterion("dateCreated <", value, "datecreated");
			return (Criteria) this;
		}

		public Criteria andDatecreatedLessThanOrEqualTo(Date value) {
			addCriterion("dateCreated <=", value, "datecreated");
			return (Criteria) this;
		}

		public Criteria andDatecreatedIn(List<Date> values) {
			addCriterion("dateCreated in", values, "datecreated");
			return (Criteria) this;
		}

		public Criteria andDatecreatedNotIn(List<Date> values) {
			addCriterion("dateCreated not in", values, "datecreated");
			return (Criteria) this;
		}

		public Criteria andDatecreatedBetween(Date value1, Date value2) {
			addCriterion("dateCreated between", value1, value2, "datecreated");
			return (Criteria) this;
		}

		public Criteria andDatecreatedNotBetween(Date value1, Date value2) {
			addCriterion("dateCreated not between", value1, value2,
					"datecreated");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedIsNull() {
			addCriterion("dateModified is null");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedIsNotNull() {
			addCriterion("dateModified is not null");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedEqualTo(Date value) {
			addCriterion("dateModified =", value, "datemodified");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedNotEqualTo(Date value) {
			addCriterion("dateModified <>", value, "datemodified");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedGreaterThan(Date value) {
			addCriterion("dateModified >", value, "datemodified");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedGreaterThanOrEqualTo(Date value) {
			addCriterion("dateModified >=", value, "datemodified");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedLessThan(Date value) {
			addCriterion("dateModified <", value, "datemodified");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedLessThanOrEqualTo(Date value) {
			addCriterion("dateModified <=", value, "datemodified");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedIn(List<Date> values) {
			addCriterion("dateModified in", values, "datemodified");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedNotIn(List<Date> values) {
			addCriterion("dateModified not in", values, "datemodified");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedBetween(Date value1, Date value2) {
			addCriterion("dateModified between", value1, value2, "datemodified");
			return (Criteria) this;
		}

		public Criteria andDatemodifiedNotBetween(Date value1, Date value2) {
			addCriterion("dateModified not between", value1, value2,
					"datemodified");
			return (Criteria) this;
		}

		public Criteria andReadLevelIsNull() {
			addCriterion("c_readLevel is null");
			return (Criteria) this;
		}

		public Criteria andReadLevelIsNotNull() {
			addCriterion("c_readLevel is not null");
			return (Criteria) this;
		}

		public Criteria andReadLevelEqualTo(String value) {
			addCriterion("c_readLevel =", value, "readLevel");
			return (Criteria) this;
		}

		public Criteria andReadLevelNotEqualTo(String value) {
			addCriterion("c_readLevel <>", value, "readLevel");
			return (Criteria) this;
		}

		public Criteria andReadLevelGreaterThan(String value) {
			addCriterion("c_readLevel >", value, "readLevel");
			return (Criteria) this;
		}

		public Criteria andReadLevelGreaterThanOrEqualTo(String value) {
			addCriterion("c_readLevel >=", value, "readLevel");
			return (Criteria) this;
		}

		public Criteria andReadLevelLessThan(String value) {
			addCriterion("c_readLevel <", value, "readLevel");
			return (Criteria) this;
		}

		public Criteria andReadLevelLessThanOrEqualTo(String value) {
			addCriterion("c_readLevel <=", value, "readLevel");
			return (Criteria) this;
		}

		public Criteria andReadLevelLike(String value) {
			addCriterion("c_readLevel like", value, "readLevel");
			return (Criteria) this;
		}

		public Criteria andReadLevelNotLike(String value) {
			addCriterion("c_readLevel not like", value, "readLevel");
			return (Criteria) this;
		}

		public Criteria andReadLevelIn(List<String> values) {
			addCriterion("c_readLevel in", values, "readLevel");
			return (Criteria) this;
		}

		public Criteria andReadLevelNotIn(List<String> values) {
			addCriterion("c_readLevel not in", values, "readLevel");
			return (Criteria) this;
		}

		public Criteria andReadLevelBetween(String value1, String value2) {
			addCriterion("c_readLevel between", value1, value2, "readLevel");
			return (Criteria) this;
		}

		public Criteria andReadLevelNotBetween(String value1, String value2) {
			addCriterion("c_readLevel not between", value1, value2, "readLevel");
			return (Criteria) this;
		}

		public Criteria andDiscriptionIsNull() {
			addCriterion("c_discription is null");
			return (Criteria) this;
		}

		public Criteria andDiscriptionIsNotNull() {
			addCriterion("c_discription is not null");
			return (Criteria) this;
		}

		public Criteria andDiscriptionEqualTo(String value) {
			addCriterion("c_discription =", value, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionNotEqualTo(String value) {
			addCriterion("c_discription <>", value, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionGreaterThan(String value) {
			addCriterion("c_discription >", value, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionGreaterThanOrEqualTo(String value) {
			addCriterion("c_discription >=", value, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionLessThan(String value) {
			addCriterion("c_discription <", value, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionLessThanOrEqualTo(String value) {
			addCriterion("c_discription <=", value, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionLike(String value) {
			addCriterion("c_discription like", value, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionNotLike(String value) {
			addCriterion("c_discription not like", value, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionIn(List<String> values) {
			addCriterion("c_discription in", values, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionNotIn(List<String> values) {
			addCriterion("c_discription not in", values, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionBetween(String value1, String value2) {
			addCriterion("c_discription between", value1, value2, "discription");
			return (Criteria) this;
		}

		public Criteria andDiscriptionNotBetween(String value1, String value2) {
			addCriterion("c_discription not between", value1, value2,
					"discription");
			return (Criteria) this;
		}

		public Criteria andOriginPlaceIsNull() {
			addCriterion("c_originPlace is null");
			return (Criteria) this;
		}

		public Criteria andOriginPlaceIsNotNull() {
			addCriterion("c_originPlace is not null");
			return (Criteria) this;
		}

		public Criteria andOriginPlaceEqualTo(String value) {
			addCriterion("c_originPlace =", value, "originPlace");
			return (Criteria) this;
		}

		public Criteria andOriginPlaceNotEqualTo(String value) {
			addCriterion("c_originPlace <>", value, "originPlace");
			return (Criteria) this;
		}

		public Criteria andOriginPlaceGreaterThan(String value) {
			addCriterion("c_originPlace >", value, "originPlace");
			return (Criteria) this;
		}

		public Criteria andOriginPlaceGreaterThanOrEqualTo(String value) {
			addCriterion("c_originPlace >=", value, "originPlace");
			return (Criteria) this;
		}

		public Criteria andOriginPlaceLessThan(String value) {
			addCriterion("c_originPlace <", value, "originPlace");
			return (Criteria) this;
		}

		public Criteria andOriginPlaceLessThanOrEqualTo(String value) {
			addCriterion("c_originPlace <=", value, "originPlace");
			return (Criteria) this;
		}

		public Criteria andOriginPlaceLike(String value) {
			addCriterion("c_originPlace like", value, "originPlace");
			return (Criteria) this;
		}

		public Criteria andOriginPlaceNotLike(String value) {
			addCriterion("c_originPlace not like", value, "originPlace");
			return (Criteria) this;
		}

		public Criteria andOriginPlaceIn(List<String> values) {
			addCriterion("c_originPlace in", values, "originPlace");
			return (Criteria) this;
		}

		public Criteria andOriginPlaceNotIn(List<String> values) {
			addCriterion("c_originPlace not in", values, "originPlace");
			return (Criteria) this;
		}

		public Criteria andOriginPlaceBetween(String value1, String value2) {
			addCriterion("c_originPlace between", value1, value2, "originPlace");
			return (Criteria) this;
		}

		public Criteria andOriginPlaceNotBetween(String value1, String value2) {
			addCriterion("c_originPlace not between", value1, value2,
					"originPlace");
			return (Criteria) this;
		}

		public Criteria andProdIconIsNull() {
			addCriterion("c_prodIcon is null");
			return (Criteria) this;
		}

		public Criteria andProdIconIsNotNull() {
			addCriterion("c_prodIcon is not null");
			return (Criteria) this;
		}

		public Criteria andProdIconEqualTo(String value) {
			addCriterion("c_prodIcon =", value, "prodIcon");
			return (Criteria) this;
		}

		public Criteria andProdIconNotEqualTo(String value) {
			addCriterion("c_prodIcon <>", value, "prodIcon");
			return (Criteria) this;
		}

		public Criteria andProdIconGreaterThan(String value) {
			addCriterion("c_prodIcon >", value, "prodIcon");
			return (Criteria) this;
		}

		public Criteria andProdIconGreaterThanOrEqualTo(String value) {
			addCriterion("c_prodIcon >=", value, "prodIcon");
			return (Criteria) this;
		}

		public Criteria andProdIconLessThan(String value) {
			addCriterion("c_prodIcon <", value, "prodIcon");
			return (Criteria) this;
		}

		public Criteria andProdIconLessThanOrEqualTo(String value) {
			addCriterion("c_prodIcon <=", value, "prodIcon");
			return (Criteria) this;
		}

		public Criteria andProdIconLike(String value) {
			addCriterion("c_prodIcon like", value, "prodIcon");
			return (Criteria) this;
		}

		public Criteria andProdIconNotLike(String value) {
			addCriterion("c_prodIcon not like", value, "prodIcon");
			return (Criteria) this;
		}

		public Criteria andProdIconIn(List<String> values) {
			addCriterion("c_prodIcon in", values, "prodIcon");
			return (Criteria) this;
		}

		public Criteria andProdIconNotIn(List<String> values) {
			addCriterion("c_prodIcon not in", values, "prodIcon");
			return (Criteria) this;
		}

		public Criteria andProdIconBetween(String value1, String value2) {
			addCriterion("c_prodIcon between", value1, value2, "prodIcon");
			return (Criteria) this;
		}

		public Criteria andProdIconNotBetween(String value1, String value2) {
			addCriterion("c_prodIcon not between", value1, value2, "prodIcon");
			return (Criteria) this;
		}

		public Criteria andVideoCoursePriceIsNull() {
			addCriterion("c_videoCoursePrice is null");
			return (Criteria) this;
		}

		public Criteria andVideoCoursePriceIsNotNull() {
			addCriterion("c_videoCoursePrice is not null");
			return (Criteria) this;
		}

		public Criteria andVideoCoursePriceEqualTo(String value) {
			addCriterion("c_videoCoursePrice =", value, "videoCoursePrice");
			return (Criteria) this;
		}

		public Criteria andVideoCoursePriceNotEqualTo(String value) {
			addCriterion("c_videoCoursePrice <>", value, "videoCoursePrice");
			return (Criteria) this;
		}

		public Criteria andVideoCoursePriceGreaterThan(String value) {
			addCriterion("c_videoCoursePrice >", value, "videoCoursePrice");
			return (Criteria) this;
		}

		public Criteria andVideoCoursePriceGreaterThanOrEqualTo(String value) {
			addCriterion("c_videoCoursePrice >=", value, "videoCoursePrice");
			return (Criteria) this;
		}

		public Criteria andVideoCoursePriceLessThan(String value) {
			addCriterion("c_videoCoursePrice <", value, "videoCoursePrice");
			return (Criteria) this;
		}

		public Criteria andVideoCoursePriceLessThanOrEqualTo(String value) {
			addCriterion("c_videoCoursePrice <=", value, "videoCoursePrice");
			return (Criteria) this;
		}

		public Criteria andVideoCoursePriceLike(String value) {
			addCriterion("c_videoCoursePrice like", value, "videoCoursePrice");
			return (Criteria) this;
		}

		public Criteria andVideoCoursePriceNotLike(String value) {
			addCriterion("c_videoCoursePrice not like", value,
					"videoCoursePrice");
			return (Criteria) this;
		}

		public Criteria andVideoCoursePriceIn(List<String> values) {
			addCriterion("c_videoCoursePrice in", values, "videoCoursePrice");
			return (Criteria) this;
		}

		public Criteria andVideoCoursePriceNotIn(List<String> values) {
			addCriterion("c_videoCoursePrice not in", values,
					"videoCoursePrice");
			return (Criteria) this;
		}

		public Criteria andVideoCoursePriceBetween(String value1, String value2) {
			addCriterion("c_videoCoursePrice between", value1, value2,
					"videoCoursePrice");
			return (Criteria) this;
		}

		public Criteria andVideoCoursePriceNotBetween(String value1,
				String value2) {
			addCriterion("c_videoCoursePrice not between", value1, value2,
					"videoCoursePrice");
			return (Criteria) this;
		}

		public Criteria andBookNameIsNull() {
			addCriterion("c_bookName is null");
			return (Criteria) this;
		}

		public Criteria andBookNameIsNotNull() {
			addCriterion("c_bookName is not null");
			return (Criteria) this;
		}

		public Criteria andBookNameEqualTo(String value) {
			addCriterion("c_bookName =", value, "bookName");
			return (Criteria) this;
		}

		public Criteria andBookNameNotEqualTo(String value) {
			addCriterion("c_bookName <>", value, "bookName");
			return (Criteria) this;
		}

		public Criteria andBookNameGreaterThan(String value) {
			addCriterion("c_bookName >", value, "bookName");
			return (Criteria) this;
		}

		public Criteria andBookNameGreaterThanOrEqualTo(String value) {
			addCriterion("c_bookName >=", value, "bookName");
			return (Criteria) this;
		}

		public Criteria andBookNameLessThan(String value) {
			addCriterion("c_bookName <", value, "bookName");
			return (Criteria) this;
		}

		public Criteria andBookNameLessThanOrEqualTo(String value) {
			addCriterion("c_bookName <=", value, "bookName");
			return (Criteria) this;
		}

		public Criteria andBookNameLike(String value) {
			addCriterion("c_bookName like", value, "bookName");
			return (Criteria) this;
		}

		public Criteria andBookNameNotLike(String value) {
			addCriterion("c_bookName not like", value, "bookName");
			return (Criteria) this;
		}

		public Criteria andBookNameIn(List<String> values) {
			addCriterion("c_bookName in", values, "bookName");
			return (Criteria) this;
		}

		public Criteria andBookNameNotIn(List<String> values) {
			addCriterion("c_bookName not in", values, "bookName");
			return (Criteria) this;
		}

		public Criteria andBookNameBetween(String value1, String value2) {
			addCriterion("c_bookName between", value1, value2, "bookName");
			return (Criteria) this;
		}

		public Criteria andBookNameNotBetween(String value1, String value2) {
			addCriterion("c_bookName not between", value1, value2, "bookName");
			return (Criteria) this;
		}

		public Criteria andVocabularyNumIsNull() {
			addCriterion("c_vocabularyNum is null");
			return (Criteria) this;
		}

		public Criteria andVocabularyNumIsNotNull() {
			addCriterion("c_vocabularyNum is not null");
			return (Criteria) this;
		}

		public Criteria andVocabularyNumEqualTo(String value) {
			addCriterion("c_vocabularyNum =", value, "vocabularyNum");
			return (Criteria) this;
		}

		public Criteria andVocabularyNumNotEqualTo(String value) {
			addCriterion("c_vocabularyNum <>", value, "vocabularyNum");
			return (Criteria) this;
		}

		public Criteria andVocabularyNumGreaterThan(String value) {
			addCriterion("c_vocabularyNum >", value, "vocabularyNum");
			return (Criteria) this;
		}

		public Criteria andVocabularyNumGreaterThanOrEqualTo(String value) {
			addCriterion("c_vocabularyNum >=", value, "vocabularyNum");
			return (Criteria) this;
		}

		public Criteria andVocabularyNumLessThan(String value) {
			addCriterion("c_vocabularyNum <", value, "vocabularyNum");
			return (Criteria) this;
		}

		public Criteria andVocabularyNumLessThanOrEqualTo(String value) {
			addCriterion("c_vocabularyNum <=", value, "vocabularyNum");
			return (Criteria) this;
		}

		public Criteria andVocabularyNumLike(String value) {
			addCriterion("c_vocabularyNum like", value, "vocabularyNum");
			return (Criteria) this;
		}

		public Criteria andVocabularyNumNotLike(String value) {
			addCriterion("c_vocabularyNum not like", value, "vocabularyNum");
			return (Criteria) this;
		}

		public Criteria andVocabularyNumIn(List<String> values) {
			addCriterion("c_vocabularyNum in", values, "vocabularyNum");
			return (Criteria) this;
		}

		public Criteria andVocabularyNumNotIn(List<String> values) {
			addCriterion("c_vocabularyNum not in", values, "vocabularyNum");
			return (Criteria) this;
		}

		public Criteria andVocabularyNumBetween(String value1, String value2) {
			addCriterion("c_vocabularyNum between", value1, value2,
					"vocabularyNum");
			return (Criteria) this;
		}

		public Criteria andVocabularyNumNotBetween(String value1, String value2) {
			addCriterion("c_vocabularyNum not between", value1, value2,
					"vocabularyNum");
			return (Criteria) this;
		}

		public Criteria andVideoDiscountPriceIsNull() {
			addCriterion("c_videoDiscountPrice is null");
			return (Criteria) this;
		}

		public Criteria andVideoDiscountPriceIsNotNull() {
			addCriterion("c_videoDiscountPrice is not null");
			return (Criteria) this;
		}

		public Criteria andVideoDiscountPriceEqualTo(String value) {
			addCriterion("c_videoDiscountPrice =", value, "videoDiscountPrice");
			return (Criteria) this;
		}

		public Criteria andVideoDiscountPriceNotEqualTo(String value) {
			addCriterion("c_videoDiscountPrice <>", value, "videoDiscountPrice");
			return (Criteria) this;
		}

		public Criteria andVideoDiscountPriceGreaterThan(String value) {
			addCriterion("c_videoDiscountPrice >", value, "videoDiscountPrice");
			return (Criteria) this;
		}

		public Criteria andVideoDiscountPriceGreaterThanOrEqualTo(String value) {
			addCriterion("c_videoDiscountPrice >=", value, "videoDiscountPrice");
			return (Criteria) this;
		}

		public Criteria andVideoDiscountPriceLessThan(String value) {
			addCriterion("c_videoDiscountPrice <", value, "videoDiscountPrice");
			return (Criteria) this;
		}

		public Criteria andVideoDiscountPriceLessThanOrEqualTo(String value) {
			addCriterion("c_videoDiscountPrice <=", value, "videoDiscountPrice");
			return (Criteria) this;
		}

		public Criteria andVideoDiscountPriceLike(String value) {
			addCriterion("c_videoDiscountPrice like", value,
					"videoDiscountPrice");
			return (Criteria) this;
		}

		public Criteria andVideoDiscountPriceNotLike(String value) {
			addCriterion("c_videoDiscountPrice not like", value,
					"videoDiscountPrice");
			return (Criteria) this;
		}

		public Criteria andVideoDiscountPriceIn(List<String> values) {
			addCriterion("c_videoDiscountPrice in", values,
					"videoDiscountPrice");
			return (Criteria) this;
		}

		public Criteria andVideoDiscountPriceNotIn(List<String> values) {
			addCriterion("c_videoDiscountPrice not in", values,
					"videoDiscountPrice");
			return (Criteria) this;
		}

		public Criteria andVideoDiscountPriceBetween(String value1,
				String value2) {
			addCriterion("c_videoDiscountPrice between", value1, value2,
					"videoDiscountPrice");
			return (Criteria) this;
		}

		public Criteria andVideoDiscountPriceNotBetween(String value1,
				String value2) {
			addCriterion("c_videoDiscountPrice not between", value1, value2,
					"videoDiscountPrice");
			return (Criteria) this;
		}

		public Criteria andTeacherIsNull() {
			addCriterion("c_teacher is null");
			return (Criteria) this;
		}

		public Criteria andTeacherIsNotNull() {
			addCriterion("c_teacher is not null");
			return (Criteria) this;
		}

		public Criteria andTeacherEqualTo(String value) {
			addCriterion("c_teacher =", value, "teacher");
			return (Criteria) this;
		}

		public Criteria andTeacherNotEqualTo(String value) {
			addCriterion("c_teacher <>", value, "teacher");
			return (Criteria) this;
		}

		public Criteria andTeacherGreaterThan(String value) {
			addCriterion("c_teacher >", value, "teacher");
			return (Criteria) this;
		}

		public Criteria andTeacherGreaterThanOrEqualTo(String value) {
			addCriterion("c_teacher >=", value, "teacher");
			return (Criteria) this;
		}

		public Criteria andTeacherLessThan(String value) {
			addCriterion("c_teacher <", value, "teacher");
			return (Criteria) this;
		}

		public Criteria andTeacherLessThanOrEqualTo(String value) {
			addCriterion("c_teacher <=", value, "teacher");
			return (Criteria) this;
		}

		public Criteria andTeacherLike(String value) {
			addCriterion("c_teacher like", value, "teacher");
			return (Criteria) this;
		}

		public Criteria andTeacherNotLike(String value) {
			addCriterion("c_teacher not like", value, "teacher");
			return (Criteria) this;
		}

		public Criteria andTeacherIn(List<String> values) {
			addCriterion("c_teacher in", values, "teacher");
			return (Criteria) this;
		}

		public Criteria andTeacherNotIn(List<String> values) {
			addCriterion("c_teacher not in", values, "teacher");
			return (Criteria) this;
		}

		public Criteria andTeacherBetween(String value1, String value2) {
			addCriterion("c_teacher between", value1, value2, "teacher");
			return (Criteria) this;
		}

		public Criteria andTeacherNotBetween(String value1, String value2) {
			addCriterion("c_teacher not between", value1, value2, "teacher");
			return (Criteria) this;
		}

		public Criteria andProdNameIsNull() {
			addCriterion("c_prodName is null");
			return (Criteria) this;
		}

		public Criteria andProdNameIsNotNull() {
			addCriterion("c_prodName is not null");
			return (Criteria) this;
		}

		public Criteria andProdNameEqualTo(String value) {
			addCriterion("c_prodName =", value, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameNotEqualTo(String value) {
			addCriterion("c_prodName <>", value, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameGreaterThan(String value) {
			addCriterion("c_prodName >", value, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameGreaterThanOrEqualTo(String value) {
			addCriterion("c_prodName >=", value, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameLessThan(String value) {
			addCriterion("c_prodName <", value, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameLessThanOrEqualTo(String value) {
			addCriterion("c_prodName <=", value, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameLike(String value) {
			addCriterion("c_prodName like", value, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameNotLike(String value) {
			addCriterion("c_prodName not like", value, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameIn(List<String> values) {
			addCriterion("c_prodName in", values, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameNotIn(List<String> values) {
			addCriterion("c_prodName not in", values, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameBetween(String value1, String value2) {
			addCriterion("c_prodName between", value1, value2, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameNotBetween(String value1, String value2) {
			addCriterion("c_prodName not between", value1, value2, "prodName");
			return (Criteria) this;
		}

		public Criteria andWordNumIsNull() {
			addCriterion("c_wordNum is null");
			return (Criteria) this;
		}

		public Criteria andWordNumIsNotNull() {
			addCriterion("c_wordNum is not null");
			return (Criteria) this;
		}

		public Criteria andWordNumEqualTo(String value) {
			addCriterion("c_wordNum =", value, "wordNum");
			return (Criteria) this;
		}

		public Criteria andWordNumNotEqualTo(String value) {
			addCriterion("c_wordNum <>", value, "wordNum");
			return (Criteria) this;
		}

		public Criteria andWordNumGreaterThan(String value) {
			addCriterion("c_wordNum >", value, "wordNum");
			return (Criteria) this;
		}

		public Criteria andWordNumGreaterThanOrEqualTo(String value) {
			addCriterion("c_wordNum >=", value, "wordNum");
			return (Criteria) this;
		}

		public Criteria andWordNumLessThan(String value) {
			addCriterion("c_wordNum <", value, "wordNum");
			return (Criteria) this;
		}

		public Criteria andWordNumLessThanOrEqualTo(String value) {
			addCriterion("c_wordNum <=", value, "wordNum");
			return (Criteria) this;
		}

		public Criteria andWordNumLike(String value) {
			addCriterion("c_wordNum like", value, "wordNum");
			return (Criteria) this;
		}

		public Criteria andWordNumNotLike(String value) {
			addCriterion("c_wordNum not like", value, "wordNum");
			return (Criteria) this;
		}

		public Criteria andWordNumIn(List<String> values) {
			addCriterion("c_wordNum in", values, "wordNum");
			return (Criteria) this;
		}

		public Criteria andWordNumNotIn(List<String> values) {
			addCriterion("c_wordNum not in", values, "wordNum");
			return (Criteria) this;
		}

		public Criteria andWordNumBetween(String value1, String value2) {
			addCriterion("c_wordNum between", value1, value2, "wordNum");
			return (Criteria) this;
		}

		public Criteria andWordNumNotBetween(String value1, String value2) {
			addCriterion("c_wordNum not between", value1, value2, "wordNum");
			return (Criteria) this;
		}

		public Criteria andTagIsNull() {
			addCriterion("c_tag is null");
			return (Criteria) this;
		}

		public Criteria andTagIsNotNull() {
			addCriterion("c_tag is not null");
			return (Criteria) this;
		}

		public Criteria andTagEqualTo(String value) {
			addCriterion("c_tag =", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotEqualTo(String value) {
			addCriterion("c_tag <>", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagGreaterThan(String value) {
			addCriterion("c_tag >", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagGreaterThanOrEqualTo(String value) {
			addCriterion("c_tag >=", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagLessThan(String value) {
			addCriterion("c_tag <", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagLessThanOrEqualTo(String value) {
			addCriterion("c_tag <=", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagLike(String value) {
			addCriterion("c_tag like", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotLike(String value) {
			addCriterion("c_tag not like", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagIn(List<String> values) {
			addCriterion("c_tag in", values, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotIn(List<String> values) {
			addCriterion("c_tag not in", values, "tag");
			return (Criteria) this;
		}

		public Criteria andTagBetween(String value1, String value2) {
			addCriterion("c_tag between", value1, value2, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotBetween(String value1, String value2) {
			addCriterion("c_tag not between", value1, value2, "tag");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("c_status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("c_status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("c_status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("c_status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("c_status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("c_status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("c_status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("c_status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("c_status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("c_status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("c_status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("c_status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("c_status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("c_status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andRecommendAgeIsNull() {
			addCriterion("c_recommendAge is null");
			return (Criteria) this;
		}

		public Criteria andRecommendAgeIsNotNull() {
			addCriterion("c_recommendAge is not null");
			return (Criteria) this;
		}

		public Criteria andRecommendAgeEqualTo(String value) {
			addCriterion("c_recommendAge =", value, "recommendAge");
			return (Criteria) this;
		}

		public Criteria andRecommendAgeNotEqualTo(String value) {
			addCriterion("c_recommendAge <>", value, "recommendAge");
			return (Criteria) this;
		}

		public Criteria andRecommendAgeGreaterThan(String value) {
			addCriterion("c_recommendAge >", value, "recommendAge");
			return (Criteria) this;
		}

		public Criteria andRecommendAgeGreaterThanOrEqualTo(String value) {
			addCriterion("c_recommendAge >=", value, "recommendAge");
			return (Criteria) this;
		}

		public Criteria andRecommendAgeLessThan(String value) {
			addCriterion("c_recommendAge <", value, "recommendAge");
			return (Criteria) this;
		}

		public Criteria andRecommendAgeLessThanOrEqualTo(String value) {
			addCriterion("c_recommendAge <=", value, "recommendAge");
			return (Criteria) this;
		}

		public Criteria andRecommendAgeLike(String value) {
			addCriterion("c_recommendAge like", value, "recommendAge");
			return (Criteria) this;
		}

		public Criteria andRecommendAgeNotLike(String value) {
			addCriterion("c_recommendAge not like", value, "recommendAge");
			return (Criteria) this;
		}

		public Criteria andRecommendAgeIn(List<String> values) {
			addCriterion("c_recommendAge in", values, "recommendAge");
			return (Criteria) this;
		}

		public Criteria andRecommendAgeNotIn(List<String> values) {
			addCriterion("c_recommendAge not in", values, "recommendAge");
			return (Criteria) this;
		}

		public Criteria andRecommendAgeBetween(String value1, String value2) {
			addCriterion("c_recommendAge between", value1, value2,
					"recommendAge");
			return (Criteria) this;
		}

		public Criteria andRecommendAgeNotBetween(String value1, String value2) {
			addCriterion("c_recommendAge not between", value1, value2,
					"recommendAge");
			return (Criteria) this;
		}

		public Criteria andATOSIsNull() {
			addCriterion("c_ATOS is null");
			return (Criteria) this;
		}

		public Criteria andATOSIsNotNull() {
			addCriterion("c_ATOS is not null");
			return (Criteria) this;
		}

		public Criteria andATOSEqualTo(String value) {
			addCriterion("c_ATOS =", value, "ATOS");
			return (Criteria) this;
		}

		public Criteria andATOSNotEqualTo(String value) {
			addCriterion("c_ATOS <>", value, "ATOS");
			return (Criteria) this;
		}

		public Criteria andATOSGreaterThan(String value) {
			addCriterion("c_ATOS >", value, "ATOS");
			return (Criteria) this;
		}

		public Criteria andATOSGreaterThanOrEqualTo(String value) {
			addCriterion("c_ATOS >=", value, "ATOS");
			return (Criteria) this;
		}

		public Criteria andATOSLessThan(String value) {
			addCriterion("c_ATOS <", value, "ATOS");
			return (Criteria) this;
		}

		public Criteria andATOSLessThanOrEqualTo(String value) {
			addCriterion("c_ATOS <=", value, "ATOS");
			return (Criteria) this;
		}

		public Criteria andATOSLike(String value) {
			addCriterion("c_ATOS like", value, "ATOS");
			return (Criteria) this;
		}

		public Criteria andATOSNotLike(String value) {
			addCriterion("c_ATOS not like", value, "ATOS");
			return (Criteria) this;
		}

		public Criteria andATOSIn(List<String> values) {
			addCriterion("c_ATOS in", values, "ATOS");
			return (Criteria) this;
		}

		public Criteria andATOSNotIn(List<String> values) {
			addCriterion("c_ATOS not in", values, "ATOS");
			return (Criteria) this;
		}

		public Criteria andATOSBetween(String value1, String value2) {
			addCriterion("c_ATOS between", value1, value2, "ATOS");
			return (Criteria) this;
		}

		public Criteria andATOSNotBetween(String value1, String value2) {
			addCriterion("c_ATOS not between", value1, value2, "ATOS");
			return (Criteria) this;
		}

		public Criteria andReadingSkillIsNull() {
			addCriterion("c_readingSkill is null");
			return (Criteria) this;
		}

		public Criteria andReadingSkillIsNotNull() {
			addCriterion("c_readingSkill is not null");
			return (Criteria) this;
		}

		public Criteria andReadingSkillEqualTo(String value) {
			addCriterion("c_readingSkill =", value, "readingSkill");
			return (Criteria) this;
		}

		public Criteria andReadingSkillNotEqualTo(String value) {
			addCriterion("c_readingSkill <>", value, "readingSkill");
			return (Criteria) this;
		}

		public Criteria andReadingSkillGreaterThan(String value) {
			addCriterion("c_readingSkill >", value, "readingSkill");
			return (Criteria) this;
		}

		public Criteria andReadingSkillGreaterThanOrEqualTo(String value) {
			addCriterion("c_readingSkill >=", value, "readingSkill");
			return (Criteria) this;
		}

		public Criteria andReadingSkillLessThan(String value) {
			addCriterion("c_readingSkill <", value, "readingSkill");
			return (Criteria) this;
		}

		public Criteria andReadingSkillLessThanOrEqualTo(String value) {
			addCriterion("c_readingSkill <=", value, "readingSkill");
			return (Criteria) this;
		}

		public Criteria andReadingSkillLike(String value) {
			addCriterion("c_readingSkill like", value, "readingSkill");
			return (Criteria) this;
		}

		public Criteria andReadingSkillNotLike(String value) {
			addCriterion("c_readingSkill not like", value, "readingSkill");
			return (Criteria) this;
		}

		public Criteria andReadingSkillIn(List<String> values) {
			addCriterion("c_readingSkill in", values, "readingSkill");
			return (Criteria) this;
		}

		public Criteria andReadingSkillNotIn(List<String> values) {
			addCriterion("c_readingSkill not in", values, "readingSkill");
			return (Criteria) this;
		}

		public Criteria andReadingSkillBetween(String value1, String value2) {
			addCriterion("c_readingSkill between", value1, value2,
					"readingSkill");
			return (Criteria) this;
		}

		public Criteria andReadingSkillNotBetween(String value1, String value2) {
			addCriterion("c_readingSkill not between", value1, value2,
					"readingSkill");
			return (Criteria) this;
		}

		public Criteria andHireadRankIsNull() {
			addCriterion("c_hireadRank is null");
			return (Criteria) this;
		}

		public Criteria andHireadRankIsNotNull() {
			addCriterion("c_hireadRank is not null");
			return (Criteria) this;
		}

		public Criteria andHireadRankEqualTo(String value) {
			addCriterion("c_hireadRank =", value, "hireadRank");
			return (Criteria) this;
		}

		public Criteria andHireadRankNotEqualTo(String value) {
			addCriterion("c_hireadRank <>", value, "hireadRank");
			return (Criteria) this;
		}

		public Criteria andHireadRankGreaterThan(String value) {
			addCriterion("c_hireadRank >", value, "hireadRank");
			return (Criteria) this;
		}

		public Criteria andHireadRankGreaterThanOrEqualTo(String value) {
			addCriterion("c_hireadRank >=", value, "hireadRank");
			return (Criteria) this;
		}

		public Criteria andHireadRankLessThan(String value) {
			addCriterion("c_hireadRank <", value, "hireadRank");
			return (Criteria) this;
		}

		public Criteria andHireadRankLessThanOrEqualTo(String value) {
			addCriterion("c_hireadRank <=", value, "hireadRank");
			return (Criteria) this;
		}

		public Criteria andHireadRankLike(String value) {
			addCriterion("c_hireadRank like", value, "hireadRank");
			return (Criteria) this;
		}

		public Criteria andHireadRankNotLike(String value) {
			addCriterion("c_hireadRank not like", value, "hireadRank");
			return (Criteria) this;
		}

		public Criteria andHireadRankIn(List<String> values) {
			addCriterion("c_hireadRank in", values, "hireadRank");
			return (Criteria) this;
		}

		public Criteria andHireadRankNotIn(List<String> values) {
			addCriterion("c_hireadRank not in", values, "hireadRank");
			return (Criteria) this;
		}

		public Criteria andHireadRankBetween(String value1, String value2) {
			addCriterion("c_hireadRank between", value1, value2, "hireadRank");
			return (Criteria) this;
		}

		public Criteria andHireadRankNotBetween(String value1, String value2) {
			addCriterion("c_hireadRank not between", value1, value2,
					"hireadRank");
			return (Criteria) this;
		}

		public Criteria andClassHourIsNull() {
			addCriterion("c_classHour is null");
			return (Criteria) this;
		}

		public Criteria andClassHourIsNotNull() {
			addCriterion("c_classHour is not null");
			return (Criteria) this;
		}

		public Criteria andClassHourEqualTo(String value) {
			addCriterion("c_classHour =", value, "classHour");
			return (Criteria) this;
		}

		public Criteria andClassHourNotEqualTo(String value) {
			addCriterion("c_classHour <>", value, "classHour");
			return (Criteria) this;
		}

		public Criteria andClassHourGreaterThan(String value) {
			addCriterion("c_classHour >", value, "classHour");
			return (Criteria) this;
		}

		public Criteria andClassHourGreaterThanOrEqualTo(String value) {
			addCriterion("c_classHour >=", value, "classHour");
			return (Criteria) this;
		}

		public Criteria andClassHourLessThan(String value) {
			addCriterion("c_classHour <", value, "classHour");
			return (Criteria) this;
		}

		public Criteria andClassHourLessThanOrEqualTo(String value) {
			addCriterion("c_classHour <=", value, "classHour");
			return (Criteria) this;
		}

		public Criteria andClassHourLike(String value) {
			addCriterion("c_classHour like", value, "classHour");
			return (Criteria) this;
		}

		public Criteria andClassHourNotLike(String value) {
			addCriterion("c_classHour not like", value, "classHour");
			return (Criteria) this;
		}

		public Criteria andClassHourIn(List<String> values) {
			addCriterion("c_classHour in", values, "classHour");
			return (Criteria) this;
		}

		public Criteria andClassHourNotIn(List<String> values) {
			addCriterion("c_classHour not in", values, "classHour");
			return (Criteria) this;
		}

		public Criteria andClassHourBetween(String value1, String value2) {
			addCriterion("c_classHour between", value1, value2, "classHour");
			return (Criteria) this;
		}

		public Criteria andClassHourNotBetween(String value1, String value2) {
			addCriterion("c_classHour not between", value1, value2, "classHour");
			return (Criteria) this;
		}

		public Criteria andExponentIsNull() {
			addCriterion("c_exponent is null");
			return (Criteria) this;
		}

		public Criteria andExponentIsNotNull() {
			addCriterion("c_exponent is not null");
			return (Criteria) this;
		}

		public Criteria andExponentEqualTo(String value) {
			addCriterion("c_exponent =", value, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentNotEqualTo(String value) {
			addCriterion("c_exponent <>", value, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentGreaterThan(String value) {
			addCriterion("c_exponent >", value, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentGreaterThanOrEqualTo(String value) {
			addCriterion("c_exponent >=", value, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentLessThan(String value) {
			addCriterion("c_exponent <", value, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentLessThanOrEqualTo(String value) {
			addCriterion("c_exponent <=", value, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentLike(String value) {
			addCriterion("c_exponent like", value, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentNotLike(String value) {
			addCriterion("c_exponent not like", value, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentIn(List<String> values) {
			addCriterion("c_exponent in", values, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentNotIn(List<String> values) {
			addCriterion("c_exponent not in", values, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentBetween(String value1, String value2) {
			addCriterion("c_exponent between", value1, value2, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentNotBetween(String value1, String value2) {
			addCriterion("c_exponent not between", value1, value2, "exponent");
			return (Criteria) this;
		}

		public Criteria andBookNameCNIsNull() {
			addCriterion("c_bookNameCN is null");
			return (Criteria) this;
		}

		public Criteria andBookNameCNIsNotNull() {
			addCriterion("c_bookNameCN is not null");
			return (Criteria) this;
		}

		public Criteria andBookNameCNEqualTo(String value) {
			addCriterion("c_bookNameCN =", value, "bookNameCN");
			return (Criteria) this;
		}

		public Criteria andBookNameCNNotEqualTo(String value) {
			addCriterion("c_bookNameCN <>", value, "bookNameCN");
			return (Criteria) this;
		}

		public Criteria andBookNameCNGreaterThan(String value) {
			addCriterion("c_bookNameCN >", value, "bookNameCN");
			return (Criteria) this;
		}

		public Criteria andBookNameCNGreaterThanOrEqualTo(String value) {
			addCriterion("c_bookNameCN >=", value, "bookNameCN");
			return (Criteria) this;
		}

		public Criteria andBookNameCNLessThan(String value) {
			addCriterion("c_bookNameCN <", value, "bookNameCN");
			return (Criteria) this;
		}

		public Criteria andBookNameCNLessThanOrEqualTo(String value) {
			addCriterion("c_bookNameCN <=", value, "bookNameCN");
			return (Criteria) this;
		}

		public Criteria andBookNameCNLike(String value) {
			addCriterion("c_bookNameCN like", value, "bookNameCN");
			return (Criteria) this;
		}

		public Criteria andBookNameCNNotLike(String value) {
			addCriterion("c_bookNameCN not like", value, "bookNameCN");
			return (Criteria) this;
		}

		public Criteria andBookNameCNIn(List<String> values) {
			addCriterion("c_bookNameCN in", values, "bookNameCN");
			return (Criteria) this;
		}

		public Criteria andBookNameCNNotIn(List<String> values) {
			addCriterion("c_bookNameCN not in", values, "bookNameCN");
			return (Criteria) this;
		}

		public Criteria andBookNameCNBetween(String value1, String value2) {
			addCriterion("c_bookNameCN between", value1, value2, "bookNameCN");
			return (Criteria) this;
		}

		public Criteria andBookNameCNNotBetween(String value1, String value2) {
			addCriterion("c_bookNameCN not between", value1, value2,
					"bookNameCN");
			return (Criteria) this;
		}

		public Criteria andBookTypeIsNull() {
			addCriterion("c_bookType is null");
			return (Criteria) this;
		}

		public Criteria andBookTypeIsNotNull() {
			addCriterion("c_bookType is not null");
			return (Criteria) this;
		}

		public Criteria andBookTypeEqualTo(String value) {
			addCriterion("c_bookType =", value, "bookType");
			return (Criteria) this;
		}

		public Criteria andBookTypeNotEqualTo(String value) {
			addCriterion("c_bookType <>", value, "bookType");
			return (Criteria) this;
		}

		public Criteria andBookTypeGreaterThan(String value) {
			addCriterion("c_bookType >", value, "bookType");
			return (Criteria) this;
		}

		public Criteria andBookTypeGreaterThanOrEqualTo(String value) {
			addCriterion("c_bookType >=", value, "bookType");
			return (Criteria) this;
		}

		public Criteria andBookTypeLessThan(String value) {
			addCriterion("c_bookType <", value, "bookType");
			return (Criteria) this;
		}

		public Criteria andBookTypeLessThanOrEqualTo(String value) {
			addCriterion("c_bookType <=", value, "bookType");
			return (Criteria) this;
		}

		public Criteria andBookTypeLike(String value) {
			addCriterion("c_bookType like", value, "bookType");
			return (Criteria) this;
		}

		public Criteria andBookTypeNotLike(String value) {
			addCriterion("c_bookType not like", value, "bookType");
			return (Criteria) this;
		}

		public Criteria andBookTypeIn(List<String> values) {
			addCriterion("c_bookType in", values, "bookType");
			return (Criteria) this;
		}

		public Criteria andBookTypeNotIn(List<String> values) {
			addCriterion("c_bookType not in", values, "bookType");
			return (Criteria) this;
		}

		public Criteria andBookTypeBetween(String value1, String value2) {
			addCriterion("c_bookType between", value1, value2, "bookType");
			return (Criteria) this;
		}

		public Criteria andBookTypeNotBetween(String value1, String value2) {
			addCriterion("c_bookType not between", value1, value2, "bookType");
			return (Criteria) this;
		}

		public Criteria andDiscountIsNull() {
			addCriterion("c_discount is null");
			return (Criteria) this;
		}

		public Criteria andDiscountIsNotNull() {
			addCriterion("c_discount is not null");
			return (Criteria) this;
		}

		public Criteria andDiscountEqualTo(String value) {
			addCriterion("c_discount =", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountNotEqualTo(String value) {
			addCriterion("c_discount <>", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountGreaterThan(String value) {
			addCriterion("c_discount >", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountGreaterThanOrEqualTo(String value) {
			addCriterion("c_discount >=", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountLessThan(String value) {
			addCriterion("c_discount <", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountLessThanOrEqualTo(String value) {
			addCriterion("c_discount <=", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountLike(String value) {
			addCriterion("c_discount like", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountNotLike(String value) {
			addCriterion("c_discount not like", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountIn(List<String> values) {
			addCriterion("c_discount in", values, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountNotIn(List<String> values) {
			addCriterion("c_discount not in", values, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountBetween(String value1, String value2) {
			addCriterion("c_discount between", value1, value2, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountNotBetween(String value1, String value2) {
			addCriterion("c_discount not between", value1, value2, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountStartIsNull() {
			addCriterion("c_discountStart is null");
			return (Criteria) this;
		}

		public Criteria andDiscountStartIsNotNull() {
			addCriterion("c_discountStart is not null");
			return (Criteria) this;
		}

		public Criteria andDiscountStartEqualTo(String value) {
			addCriterion("c_discountStart =", value, "discountStart");
			return (Criteria) this;
		}

		public Criteria andDiscountStartNotEqualTo(String value) {
			addCriterion("c_discountStart <>", value, "discountStart");
			return (Criteria) this;
		}

		public Criteria andDiscountStartGreaterThan(String value) {
			addCriterion("c_discountStart >", value, "discountStart");
			return (Criteria) this;
		}

		public Criteria andDiscountStartGreaterThanOrEqualTo(String value) {
			addCriterion("c_discountStart >=", value, "discountStart");
			return (Criteria) this;
		}

		public Criteria andDiscountStartLessThan(String value) {
			addCriterion("c_discountStart <", value, "discountStart");
			return (Criteria) this;
		}

		public Criteria andDiscountStartLessThanOrEqualTo(String value) {
			addCriterion("c_discountStart <=", value, "discountStart");
			return (Criteria) this;
		}

		public Criteria andDiscountStartLike(String value) {
			addCriterion("c_discountStart like", value, "discountStart");
			return (Criteria) this;
		}

		public Criteria andDiscountStartNotLike(String value) {
			addCriterion("c_discountStart not like", value, "discountStart");
			return (Criteria) this;
		}

		public Criteria andDiscountStartIn(List<String> values) {
			addCriterion("c_discountStart in", values, "discountStart");
			return (Criteria) this;
		}

		public Criteria andDiscountStartNotIn(List<String> values) {
			addCriterion("c_discountStart not in", values, "discountStart");
			return (Criteria) this;
		}

		public Criteria andDiscountStartBetween(String value1, String value2) {
			addCriterion("c_discountStart between", value1, value2,
					"discountStart");
			return (Criteria) this;
		}

		public Criteria andDiscountStartNotBetween(String value1, String value2) {
			addCriterion("c_discountStart not between", value1, value2,
					"discountStart");
			return (Criteria) this;
		}

		public Criteria andDiscountEndIsNull() {
			addCriterion("c_discountEnd is null");
			return (Criteria) this;
		}

		public Criteria andDiscountEndIsNotNull() {
			addCriterion("c_discountEnd is not null");
			return (Criteria) this;
		}

		public Criteria andDiscountEndEqualTo(String value) {
			addCriterion("c_discountEnd =", value, "discountEnd");
			return (Criteria) this;
		}

		public Criteria andDiscountEndNotEqualTo(String value) {
			addCriterion("c_discountEnd <>", value, "discountEnd");
			return (Criteria) this;
		}

		public Criteria andDiscountEndGreaterThan(String value) {
			addCriterion("c_discountEnd >", value, "discountEnd");
			return (Criteria) this;
		}

		public Criteria andDiscountEndGreaterThanOrEqualTo(String value) {
			addCriterion("c_discountEnd >=", value, "discountEnd");
			return (Criteria) this;
		}

		public Criteria andDiscountEndLessThan(String value) {
			addCriterion("c_discountEnd <", value, "discountEnd");
			return (Criteria) this;
		}

		public Criteria andDiscountEndLessThanOrEqualTo(String value) {
			addCriterion("c_discountEnd <=", value, "discountEnd");
			return (Criteria) this;
		}

		public Criteria andDiscountEndLike(String value) {
			addCriterion("c_discountEnd like", value, "discountEnd");
			return (Criteria) this;
		}

		public Criteria andDiscountEndNotLike(String value) {
			addCriterion("c_discountEnd not like", value, "discountEnd");
			return (Criteria) this;
		}

		public Criteria andDiscountEndIn(List<String> values) {
			addCriterion("c_discountEnd in", values, "discountEnd");
			return (Criteria) this;
		}

		public Criteria andDiscountEndNotIn(List<String> values) {
			addCriterion("c_discountEnd not in", values, "discountEnd");
			return (Criteria) this;
		}

		public Criteria andDiscountEndBetween(String value1, String value2) {
			addCriterion("c_discountEnd between", value1, value2, "discountEnd");
			return (Criteria) this;
		}

		public Criteria andDiscountEndNotBetween(String value1, String value2) {
			addCriterion("c_discountEnd not between", value1, value2,
					"discountEnd");
			return (Criteria) this;
		}

		public Criteria andDiscountTitleIsNull() {
			addCriterion("c_discountTitle is null");
			return (Criteria) this;
		}

		public Criteria andDiscountTitleIsNotNull() {
			addCriterion("c_discountTitle is not null");
			return (Criteria) this;
		}

		public Criteria andDiscountTitleEqualTo(String value) {
			addCriterion("c_discountTitle =", value, "discountTitle");
			return (Criteria) this;
		}

		public Criteria andDiscountTitleNotEqualTo(String value) {
			addCriterion("c_discountTitle <>", value, "discountTitle");
			return (Criteria) this;
		}

		public Criteria andDiscountTitleGreaterThan(String value) {
			addCriterion("c_discountTitle >", value, "discountTitle");
			return (Criteria) this;
		}

		public Criteria andDiscountTitleGreaterThanOrEqualTo(String value) {
			addCriterion("c_discountTitle >=", value, "discountTitle");
			return (Criteria) this;
		}

		public Criteria andDiscountTitleLessThan(String value) {
			addCriterion("c_discountTitle <", value, "discountTitle");
			return (Criteria) this;
		}

		public Criteria andDiscountTitleLessThanOrEqualTo(String value) {
			addCriterion("c_discountTitle <=", value, "discountTitle");
			return (Criteria) this;
		}

		public Criteria andDiscountTitleLike(String value) {
			addCriterion("c_discountTitle like", value, "discountTitle");
			return (Criteria) this;
		}

		public Criteria andDiscountTitleNotLike(String value) {
			addCriterion("c_discountTitle not like", value, "discountTitle");
			return (Criteria) this;
		}

		public Criteria andDiscountTitleIn(List<String> values) {
			addCriterion("c_discountTitle in", values, "discountTitle");
			return (Criteria) this;
		}

		public Criteria andDiscountTitleNotIn(List<String> values) {
			addCriterion("c_discountTitle not in", values, "discountTitle");
			return (Criteria) this;
		}

		public Criteria andDiscountTitleBetween(String value1, String value2) {
			addCriterion("c_discountTitle between", value1, value2,
					"discountTitle");
			return (Criteria) this;
		}

		public Criteria andDiscountTitleNotBetween(String value1, String value2) {
			addCriterion("c_discountTitle not between", value1, value2,
					"discountTitle");
			return (Criteria) this;
		}

		public Criteria andPostFreeTalkRequirementIsNull() {
			addCriterion("c_postFreeTalkRequirement is null");
			return (Criteria) this;
		}

		public Criteria andPostFreeTalkRequirementIsNotNull() {
			addCriterion("c_postFreeTalkRequirement is not null");
			return (Criteria) this;
		}

		public Criteria andPostFreeTalkRequirementEqualTo(String value) {
			addCriterion("c_postFreeTalkRequirement =", value,
					"postFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPostFreeTalkRequirementNotEqualTo(String value) {
			addCriterion("c_postFreeTalkRequirement <>", value,
					"postFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPostFreeTalkRequirementGreaterThan(String value) {
			addCriterion("c_postFreeTalkRequirement >", value,
					"postFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPostFreeTalkRequirementGreaterThanOrEqualTo(
				String value) {
			addCriterion("c_postFreeTalkRequirement >=", value,
					"postFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPostFreeTalkRequirementLessThan(String value) {
			addCriterion("c_postFreeTalkRequirement <", value,
					"postFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPostFreeTalkRequirementLessThanOrEqualTo(String value) {
			addCriterion("c_postFreeTalkRequirement <=", value,
					"postFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPostFreeTalkRequirementLike(String value) {
			addCriterion("c_postFreeTalkRequirement like", value,
					"postFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPostFreeTalkRequirementNotLike(String value) {
			addCriterion("c_postFreeTalkRequirement not like", value,
					"postFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPostFreeTalkRequirementIn(List<String> values) {
			addCriterion("c_postFreeTalkRequirement in", values,
					"postFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPostFreeTalkRequirementNotIn(List<String> values) {
			addCriterion("c_postFreeTalkRequirement not in", values,
					"postFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPostFreeTalkRequirementBetween(String value1,
				String value2) {
			addCriterion("c_postFreeTalkRequirement between", value1, value2,
					"postFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPostFreeTalkRequirementNotBetween(String value1,
				String value2) {
			addCriterion("c_postFreeTalkRequirement not between", value1,
					value2, "postFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPreFreeTalkRequirementIsNull() {
			addCriterion("c_preFreeTalkRequirement is null");
			return (Criteria) this;
		}

		public Criteria andPreFreeTalkRequirementIsNotNull() {
			addCriterion("c_preFreeTalkRequirement is not null");
			return (Criteria) this;
		}

		public Criteria andPreFreeTalkRequirementEqualTo(String value) {
			addCriterion("c_preFreeTalkRequirement =", value,
					"preFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPreFreeTalkRequirementNotEqualTo(String value) {
			addCriterion("c_preFreeTalkRequirement <>", value,
					"preFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPreFreeTalkRequirementGreaterThan(String value) {
			addCriterion("c_preFreeTalkRequirement >", value,
					"preFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPreFreeTalkRequirementGreaterThanOrEqualTo(
				String value) {
			addCriterion("c_preFreeTalkRequirement >=", value,
					"preFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPreFreeTalkRequirementLessThan(String value) {
			addCriterion("c_preFreeTalkRequirement <", value,
					"preFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPreFreeTalkRequirementLessThanOrEqualTo(String value) {
			addCriterion("c_preFreeTalkRequirement <=", value,
					"preFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPreFreeTalkRequirementLike(String value) {
			addCriterion("c_preFreeTalkRequirement like", value,
					"preFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPreFreeTalkRequirementNotLike(String value) {
			addCriterion("c_preFreeTalkRequirement not like", value,
					"preFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPreFreeTalkRequirementIn(List<String> values) {
			addCriterion("c_preFreeTalkRequirement in", values,
					"preFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPreFreeTalkRequirementNotIn(List<String> values) {
			addCriterion("c_preFreeTalkRequirement not in", values,
					"preFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPreFreeTalkRequirementBetween(String value1,
				String value2) {
			addCriterion("c_preFreeTalkRequirement between", value1, value2,
					"preFreeTalkRequirement");
			return (Criteria) this;
		}

		public Criteria andPreFreeTalkRequirementNotBetween(String value1,
				String value2) {
			addCriterion("c_preFreeTalkRequirement not between", value1,
					value2, "preFreeTalkRequirement");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table app_fd_ec_product
	 * @mbggenerated  Fri Jul 07 11:49:28 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_fd_ec_product
     *
     * @mbggenerated do_not_delete_during_merge Mon May 15 16:53:45 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}