package com.wally.hiread.model.product;

import java.util.Date;
import java.util.List;

public class ReadPractise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_read_practise.id
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_read_practise.dateCreated
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    private Date datecreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_read_practise.dateModified
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    private Date datemodified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_read_practise.c_chapter
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    private String chapter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_read_practise.c_paragraph
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    private String paragraph;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_read_practise.c_product_id
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_read_practise.c_audio
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    private String audio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_read_practise.c_page
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    private String page;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_read_practise.c_text
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_read_practise.c_unit_id
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    private String unitId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_read_practise.id
     *
     * @return the value of app_fd_ec_read_practise.id
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_read_practise.id
     *
     * @param id the value for app_fd_ec_read_practise.id
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_read_practise.dateCreated
     *
     * @return the value of app_fd_ec_read_practise.dateCreated
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public Date getDatecreated() {
        return datecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_read_practise.dateCreated
     *
     * @param datecreated the value for app_fd_ec_read_practise.dateCreated
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public void setDatecreated(Date datecreated) {
        this.datecreated = datecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_read_practise.dateModified
     *
     * @return the value of app_fd_ec_read_practise.dateModified
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public Date getDatemodified() {
        return datemodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_read_practise.dateModified
     *
     * @param datemodified the value for app_fd_ec_read_practise.dateModified
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public void setDatemodified(Date datemodified) {
        this.datemodified = datemodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_read_practise.c_chapter
     *
     * @return the value of app_fd_ec_read_practise.c_chapter
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public String getChapter() {
        return chapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_read_practise.c_chapter
     *
     * @param chapter the value for app_fd_ec_read_practise.c_chapter
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public void setChapter(String chapter) {
        this.chapter = chapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_read_practise.c_paragraph
     *
     * @return the value of app_fd_ec_read_practise.c_paragraph
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public String getParagraph() {
        return paragraph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_read_practise.c_paragraph
     *
     * @param paragraph the value for app_fd_ec_read_practise.c_paragraph
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public void setParagraph(String paragraph) {
        this.paragraph = paragraph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_read_practise.c_product_id
     *
     * @return the value of app_fd_ec_read_practise.c_product_id
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_read_practise.c_product_id
     *
     * @param productId the value for app_fd_ec_read_practise.c_product_id
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_read_practise.c_audio
     *
     * @return the value of app_fd_ec_read_practise.c_audio
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public String getAudio() {
        return audio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_read_practise.c_audio
     *
     * @param audio the value for app_fd_ec_read_practise.c_audio
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public void setAudio(String audio) {
        this.audio = audio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_read_practise.c_page
     *
     * @return the value of app_fd_ec_read_practise.c_page
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public String getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_read_practise.c_page
     *
     * @param page the value for app_fd_ec_read_practise.c_page
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public void setPage(String page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_read_practise.c_text
     *
     * @return the value of app_fd_ec_read_practise.c_text
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_read_practise.c_text
     *
     * @param text the value for app_fd_ec_read_practise.c_text
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_read_practise.c_unit_id
     *
     * @return the value of app_fd_ec_read_practise.c_unit_id
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public String getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_read_practise.c_unit_id
     *
     * @param unitId the value for app_fd_ec_read_practise.c_unit_id
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    public static final String TABLE_NAME="ec_read_practise";
    private List<UserRead> userReads;

    public List<UserRead> getUserReads() {
        return userReads;
    }

    public void setUserReads(List<UserRead> userReads) {
        this.userReads = userReads;
    }
}