package com.wally.hiread.model.product;

import java.util.Date;
import java.util.List;

public class Unit {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.id
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.dateCreated
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private Date datecreated;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.dateModified
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private Date datemodified;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.c_chapter
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private String chapter;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.c_videoDurationSec
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private String videoDurationSec;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.c_unitNo
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private String unitNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.c_videoDurationMin
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private String videoDurationMin;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.c_unitName
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private String unitName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.c_attachment
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private String attachment;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.c_product_id
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private String productId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.c_video
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private String video;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.c_pausePoint
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private String pausePoint;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.c_previewInstruction
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private String previewInstruction;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.c_previewType
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private String previewType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.c_previewParagraph
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private String previewParagraph;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.c_previewAudio
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private String previewAudio;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.c_previewVideo
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private String previewVideo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.c_previewText
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private String previewText;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.c_previewImage
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private String previewImage;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.c_previewPage
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private String previewPage;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_unit.c_page
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	private String cPage;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.id
	 * @return  the value of app_fd_ec_unit.id
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.id
	 * @param id  the value for app_fd_ec_unit.id
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.dateCreated
	 * @return  the value of app_fd_ec_unit.dateCreated
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public Date getDatecreated() {
		return datecreated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.dateCreated
	 * @param datecreated  the value for app_fd_ec_unit.dateCreated
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.dateModified
	 * @return  the value of app_fd_ec_unit.dateModified
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public Date getDatemodified() {
		return datemodified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.dateModified
	 * @param datemodified  the value for app_fd_ec_unit.dateModified
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.c_chapter
	 * @return  the value of app_fd_ec_unit.c_chapter
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public String getChapter() {
		return chapter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.c_chapter
	 * @param chapter  the value for app_fd_ec_unit.c_chapter
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setChapter(String chapter) {
		this.chapter = chapter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.c_videoDurationSec
	 * @return  the value of app_fd_ec_unit.c_videoDurationSec
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public String getVideoDurationSec() {
		return videoDurationSec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.c_videoDurationSec
	 * @param videoDurationSec  the value for app_fd_ec_unit.c_videoDurationSec
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setVideoDurationSec(String videoDurationSec) {
		this.videoDurationSec = videoDurationSec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.c_unitNo
	 * @return  the value of app_fd_ec_unit.c_unitNo
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public String getUnitNo() {
		return unitNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.c_unitNo
	 * @param unitNo  the value for app_fd_ec_unit.c_unitNo
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setUnitNo(String unitNo) {
		this.unitNo = unitNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.c_videoDurationMin
	 * @return  the value of app_fd_ec_unit.c_videoDurationMin
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public String getVideoDurationMin() {
		return videoDurationMin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.c_videoDurationMin
	 * @param videoDurationMin  the value for app_fd_ec_unit.c_videoDurationMin
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setVideoDurationMin(String videoDurationMin) {
		this.videoDurationMin = videoDurationMin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.c_unitName
	 * @return  the value of app_fd_ec_unit.c_unitName
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public String getUnitName() {
		return unitName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.c_unitName
	 * @param unitName  the value for app_fd_ec_unit.c_unitName
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.c_attachment
	 * @return  the value of app_fd_ec_unit.c_attachment
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public String getAttachment() {
		return attachment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.c_attachment
	 * @param attachment  the value for app_fd_ec_unit.c_attachment
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.c_product_id
	 * @return  the value of app_fd_ec_unit.c_product_id
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public String getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.c_product_id
	 * @param productId  the value for app_fd_ec_unit.c_product_id
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setProductId(String productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.c_video
	 * @return  the value of app_fd_ec_unit.c_video
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public String getVideo() {
		return video;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.c_video
	 * @param video  the value for app_fd_ec_unit.c_video
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setVideo(String video) {
		this.video = video;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.c_pausePoint
	 * @return  the value of app_fd_ec_unit.c_pausePoint
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public String getPausePoint() {
		return pausePoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.c_pausePoint
	 * @param pausePoint  the value for app_fd_ec_unit.c_pausePoint
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setPausePoint(String pausePoint) {
		this.pausePoint = pausePoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.c_previewInstruction
	 * @return  the value of app_fd_ec_unit.c_previewInstruction
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public String getPreviewInstruction() {
		return previewInstruction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.c_previewInstruction
	 * @param previewInstruction  the value for app_fd_ec_unit.c_previewInstruction
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setPreviewInstruction(String previewInstruction) {
		this.previewInstruction = previewInstruction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.c_previewType
	 * @return  the value of app_fd_ec_unit.c_previewType
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public String getPreviewType() {
		return previewType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.c_previewType
	 * @param previewType  the value for app_fd_ec_unit.c_previewType
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setPreviewType(String previewType) {
		this.previewType = previewType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.c_previewParagraph
	 * @return  the value of app_fd_ec_unit.c_previewParagraph
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public String getPreviewParagraph() {
		return previewParagraph;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.c_previewParagraph
	 * @param previewParagraph  the value for app_fd_ec_unit.c_previewParagraph
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setPreviewParagraph(String previewParagraph) {
		this.previewParagraph = previewParagraph;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.c_previewAudio
	 * @return  the value of app_fd_ec_unit.c_previewAudio
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public String getPreviewAudio() {
		return previewAudio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.c_previewAudio
	 * @param previewAudio  the value for app_fd_ec_unit.c_previewAudio
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setPreviewAudio(String previewAudio) {
		this.previewAudio = previewAudio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.c_previewVideo
	 * @return  the value of app_fd_ec_unit.c_previewVideo
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public String getPreviewVideo() {
		return previewVideo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.c_previewVideo
	 * @param previewVideo  the value for app_fd_ec_unit.c_previewVideo
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setPreviewVideo(String previewVideo) {
		this.previewVideo = previewVideo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.c_previewText
	 * @return  the value of app_fd_ec_unit.c_previewText
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public String getPreviewText() {
		return previewText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.c_previewText
	 * @param previewText  the value for app_fd_ec_unit.c_previewText
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setPreviewText(String previewText) {
		this.previewText = previewText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.c_previewImage
	 * @return  the value of app_fd_ec_unit.c_previewImage
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public String getPreviewImage() {
		return previewImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.c_previewImage
	 * @param previewImage  the value for app_fd_ec_unit.c_previewImage
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setPreviewImage(String previewImage) {
		this.previewImage = previewImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.c_previewPage
	 * @return  the value of app_fd_ec_unit.c_previewPage
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public String getPreviewPage() {
		return previewPage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.c_previewPage
	 * @param previewPage  the value for app_fd_ec_unit.c_previewPage
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setPreviewPage(String previewPage) {
		this.previewPage = previewPage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_unit.c_page
	 * @return  the value of app_fd_ec_unit.c_page
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public String getcPage() {
		return cPage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_unit.c_page
	 * @param cPage  the value for app_fd_ec_unit.c_page
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	public void setcPage(String cPage) {
		this.cPage = cPage;
	}

	public static final String TABLE_NAME="ec_unit";

	private Product product;

	private List<Practise> practises;

	private List<UnitSection> unitSections;
	private List<UnitHint> unitHints;
	private List<UnitAudio> unitAudios;
	private List<Integer> pauseList;
	private boolean unitLocked;
	private boolean previewLocked;
	private boolean previewHWLocked;
	private boolean videoLocked;
	private boolean reviewHWLocked;
	private String statusForUpdate;
	private int videoTime;
	private int unitAudiosTime;
	private int mediaTime;

	public int getVideoTime() {
		return videoTime;
	}

	public void setVideoTime(int videoTime) {
		this.videoTime = videoTime;
	}

	public int getUnitAudiosTime() {
		return unitAudiosTime;
	}

	public void setUnitAudiosTime(int unitAudiosTime) {
		this.unitAudiosTime = unitAudiosTime;
	}

	public int getMediaTime() {
		return mediaTime;
	}

	public void setMediaTime(int mediaTime) {
		this.mediaTime = mediaTime;
	}

	public String getStatusForUpdate() {
		return statusForUpdate;
	}

	public void setStatusForUpdate(String statusForUpdate) {
		this.statusForUpdate = statusForUpdate;
	}

	public boolean isUnitLocked() {
		return unitLocked;
	}

	public void setUnitLocked(boolean unitLocked) {
		this.unitLocked = unitLocked;
	}

	public boolean isPreviewLocked() {
		return previewLocked;
	}

	public void setPreviewLocked(boolean previewLocked) {
		this.previewLocked = previewLocked;
	}

	public boolean isPreviewHWLocked() {
		return previewHWLocked;
	}

	public void setPreviewHWLocked(boolean previewHWLocked) {
		this.previewHWLocked = previewHWLocked;
	}

	public boolean isVideoLocked() {
		return videoLocked;
	}

	public void setVideoLocked(boolean videoLocked) {
		this.videoLocked = videoLocked;
	}

	public boolean isReviewHWLocked() {
		return reviewHWLocked;
	}

	public void setReviewHWLocked(boolean reviewHWLocked) {
		this.reviewHWLocked = reviewHWLocked;
	}

	public List<Integer> getPauseList() {
		return pauseList;
	}

	public void setPauseList(List<Integer> pauseList) {
		this.pauseList = pauseList;
	}

	public List<UnitAudio> getUnitAudios() {
		return unitAudios;
	}

	public void setUnitAudios(List<UnitAudio> unitAudios) {
		this.unitAudios = unitAudios;
	}

	public List<UnitHint> getUnitHints() {
		return unitHints;
	}

	public void setUnitHints(List<UnitHint> unitHints) {
		this.unitHints = unitHints;
	}


	public List<UnitSection> getUnitSections() {
		return unitSections;
	}

	public void setUnitSections(List<UnitSection> unitSections) {
		this.unitSections = unitSections;
	}

	public List<Practise> getPractises() {
		return practises;
	}

	public void setPractises(List<Practise> practises) {
		this.practises = practises;
	}

	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

}