package com.wally.hiread.model.product;

import java.util.Date;

public class UserRead {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_user_read.id
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_user_read.dateCreated
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    private Date datecreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_user_read.dateModified
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    private Date datemodified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_user_read.c_shared
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    private String shared;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_user_read.c_audioFile
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    private String audioFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_user_read.c_read_practise_id
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    private String readPractiseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_user_read.c_user_id
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_user_read.c_like
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    private String like;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_user_read.c_sharedTime
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    private String sharedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_user_read.c_comment
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_user_read.id
     *
     * @return the value of app_fd_ec_user_read.id
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_user_read.id
     *
     * @param id the value for app_fd_ec_user_read.id
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_user_read.dateCreated
     *
     * @return the value of app_fd_ec_user_read.dateCreated
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public Date getDatecreated() {
        return datecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_user_read.dateCreated
     *
     * @param datecreated the value for app_fd_ec_user_read.dateCreated
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public void setDatecreated(Date datecreated) {
        this.datecreated = datecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_user_read.dateModified
     *
     * @return the value of app_fd_ec_user_read.dateModified
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public Date getDatemodified() {
        return datemodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_user_read.dateModified
     *
     * @param datemodified the value for app_fd_ec_user_read.dateModified
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public void setDatemodified(Date datemodified) {
        this.datemodified = datemodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_user_read.c_shared
     *
     * @return the value of app_fd_ec_user_read.c_shared
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public String getShared() {
        return shared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_user_read.c_shared
     *
     * @param shared the value for app_fd_ec_user_read.c_shared
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public void setShared(String shared) {
        this.shared = shared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_user_read.c_audioFile
     *
     * @return the value of app_fd_ec_user_read.c_audioFile
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public String getAudioFile() {
        return audioFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_user_read.c_audioFile
     *
     * @param audioFile the value for app_fd_ec_user_read.c_audioFile
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public void setAudioFile(String audioFile) {
        this.audioFile = audioFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_user_read.c_read_practise_id
     *
     * @return the value of app_fd_ec_user_read.c_read_practise_id
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public String getReadPractiseId() {
        return readPractiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_user_read.c_read_practise_id
     *
     * @param readPractiseId the value for app_fd_ec_user_read.c_read_practise_id
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public void setReadPractiseId(String readPractiseId) {
        this.readPractiseId = readPractiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_user_read.c_user_id
     *
     * @return the value of app_fd_ec_user_read.c_user_id
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_user_read.c_user_id
     *
     * @param userId the value for app_fd_ec_user_read.c_user_id
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_user_read.c_like
     *
     * @return the value of app_fd_ec_user_read.c_like
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public String getLike() {
        return like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_user_read.c_like
     *
     * @param like the value for app_fd_ec_user_read.c_like
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public void setLike(String like) {
        this.like = like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_user_read.c_sharedTime
     *
     * @return the value of app_fd_ec_user_read.c_sharedTime
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public String getSharedTime() {
        return sharedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_user_read.c_sharedTime
     *
     * @param sharedTime the value for app_fd_ec_user_read.c_sharedTime
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public void setSharedTime(String sharedTime) {
        this.sharedTime = sharedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_user_read.c_comment
     *
     * @return the value of app_fd_ec_user_read.c_comment
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_user_read.c_comment
     *
     * @param comment the value for app_fd_ec_user_read.c_comment
     *
     * @mbggenerated Mon Jun 26 10:18:11 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    public static final String TABLE_NAME="ec_user_read";

    private ReadPractise readPractise;

    private String dateCreatedTime;

    private String nDaysBefore;

    public String getnDaysBefore() {
        return nDaysBefore;
    }

    public void setnDaysBefore(String nDaysBefore) {
        this.nDaysBefore = nDaysBefore;
    }

    public String getDateCreatedTime() {
        return dateCreatedTime;
    }

    public void setDateCreatedTime(String dateCreatedTime) {
        this.dateCreatedTime = dateCreatedTime;
    }

    public ReadPractise getReadPractise() {
        return readPractise;
    }

    public void setReadPractise(ReadPractise readPractise) {
        this.readPractise = readPractise;
    }
}