package com.wally.hiread.dao.product;

import com.wally.hiread.model.product.PractiseOpt;
import com.wally.hiread.model.product.PractiseOptExample;
import java.util.List;

public interface PractiseOptMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_practise_opt
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	int countByExample(PractiseOptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_practise_opt
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_practise_opt
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	int insert(PractiseOpt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_practise_opt
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	int insertSelective(PractiseOpt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_practise_opt
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	List<PractiseOpt> selectByExample(PractiseOptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_practise_opt
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	PractiseOpt selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_practise_opt
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	int updateByPrimaryKeySelective(PractiseOpt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_practise_opt
	 * @mbggenerated  Tue Aug 01 09:49:07 CST 2017
	 */
	int updateByPrimaryKey(PractiseOpt record);
}