package com.wally.hiread.dao.product;

import com.wally.hiread.model.product.ReadPractise;
import com.wally.hiread.model.product.ReadPractiseExample;
import java.util.List;

public interface ReadPractiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_read_practise
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    int countByExample(ReadPractiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_read_practise
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_read_practise
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    int insert(ReadPractise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_read_practise
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    int insertSelective(ReadPractise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_read_practise
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    List<ReadPractise> selectByExample(ReadPractiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_read_practise
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    ReadPractise selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_read_practise
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    int updateByPrimaryKeySelective(ReadPractise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_read_practise
     *
     * @mbggenerated Mon Jun 26 10:16:00 CST 2017
     */
    int updateByPrimaryKey(ReadPractise record);
}