package com.wally.hiread.dao.product;

import com.wally.hiread.model.product.TeacherComment;
import com.wally.hiread.model.product.TeacherCommentExample;
import java.util.List;

public interface TeacherCommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_teacher_comment
	 * @mbggenerated  Tue Aug 29 15:54:34 CST 2017
	 */
	int countByExample(TeacherCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_teacher_comment
	 * @mbggenerated  Tue Aug 29 15:54:34 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_teacher_comment
	 * @mbggenerated  Tue Aug 29 15:54:34 CST 2017
	 */
	int insert(TeacherComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_teacher_comment
	 * @mbggenerated  Tue Aug 29 15:54:34 CST 2017
	 */
	int insertSelective(TeacherComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_teacher_comment
	 * @mbggenerated  Tue Aug 29 15:54:34 CST 2017
	 */
	List<TeacherComment> selectByExample(TeacherCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_teacher_comment
	 * @mbggenerated  Tue Aug 29 15:54:34 CST 2017
	 */
	TeacherComment selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_teacher_comment
	 * @mbggenerated  Tue Aug 29 15:54:34 CST 2017
	 */
	int updateByPrimaryKeySelective(TeacherComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_teacher_comment
	 * @mbggenerated  Tue Aug 29 15:54:34 CST 2017
	 */
	int updateByPrimaryKey(TeacherComment record);
}