package com.wally.hiread.dao.product;

import com.wally.hiread.model.product.UnitAudio;
import com.wally.hiread.model.product.UnitAudioExample;
import java.util.List;

public interface UnitAudioMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_unit_audio
	 * @mbggenerated  Tue Jul 11 15:00:20 CST 2017
	 */
	int countByExample(UnitAudioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_unit_audio
	 * @mbggenerated  Tue Jul 11 15:00:20 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_unit_audio
	 * @mbggenerated  Tue Jul 11 15:00:20 CST 2017
	 */
	int insert(UnitAudio record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_unit_audio
	 * @mbggenerated  Tue Jul 11 15:00:20 CST 2017
	 */
	int insertSelective(UnitAudio record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_unit_audio
	 * @mbggenerated  Tue Jul 11 15:00:20 CST 2017
	 */
	List<UnitAudio> selectByExample(UnitAudioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_unit_audio
	 * @mbggenerated  Tue Jul 11 15:00:20 CST 2017
	 */
	UnitAudio selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_unit_audio
	 * @mbggenerated  Tue Jul 11 15:00:20 CST 2017
	 */
	int updateByPrimaryKeySelective(UnitAudio record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_unit_audio
	 * @mbggenerated  Tue Jul 11 15:00:20 CST 2017
	 */
	int updateByPrimaryKey(UnitAudio record);
}