package com.wally.hiread.dao.product;

import com.wally.hiread.model.product.Unit;
import com.wally.hiread.model.product.UnitExample;
import java.util.List;

public interface UnitMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_unit
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	int countByExample(UnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_unit
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_unit
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	int insert(Unit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_unit
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	int insertSelective(Unit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_unit
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	List<Unit> selectByExampleWithBLOBs(UnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_unit
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	List<Unit> selectByExample(UnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_unit
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	Unit selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_unit
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	int updateByPrimaryKeySelective(Unit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_unit
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(Unit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_unit
	 * @mbggenerated  Mon Jun 26 09:57:30 CST 2017
	 */
	int updateByPrimaryKey(Unit record);
}