package com.wally.hiread.dao.product;

import com.wally.hiread.model.product.UserProduct;
import com.wally.hiread.model.product.UserProductExample;
import java.util.List;

public interface UserProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_product
     *
     * @mbggenerated Mon May 22 16:27:55 CST 2017
     */
    int countByExample(UserProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_product
     *
     * @mbggenerated Mon May 22 16:27:55 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_product
     *
     * @mbggenerated Mon May 22 16:27:55 CST 2017
     */
    int insert(UserProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_product
     *
     * @mbggenerated Mon May 22 16:27:55 CST 2017
     */
    int insertSelective(UserProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_product
     *
     * @mbggenerated Mon May 22 16:27:55 CST 2017
     */
    List<UserProduct> selectByExample(UserProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_product
     *
     * @mbggenerated Mon May 22 16:27:55 CST 2017
     */
    UserProduct selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_product
     *
     * @mbggenerated Mon May 22 16:27:55 CST 2017
     */
    int updateByPrimaryKeySelective(UserProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_product
     *
     * @mbggenerated Mon May 22 16:27:55 CST 2017
     */
    int updateByPrimaryKey(UserProduct record);
}