package com.wally.hiread.dao.product;

import com.wally.hiread.model.product.UserVocab;
import com.wally.hiread.model.product.UserVocabExample;
import java.util.List;

public interface UserVocabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_vocab
     *
     * @mbggenerated Tue Aug 08 09:36:12 CST 2017
     */
    int countByExample(UserVocabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_vocab
     *
     * @mbggenerated Tue Aug 08 09:36:12 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_vocab
     *
     * @mbggenerated Tue Aug 08 09:36:12 CST 2017
     */
    int insert(UserVocab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_vocab
     *
     * @mbggenerated Tue Aug 08 09:36:12 CST 2017
     */
    int insertSelective(UserVocab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_vocab
     *
     * @mbggenerated Tue Aug 08 09:36:12 CST 2017
     */
    List<UserVocab> selectByExample(UserVocabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_vocab
     *
     * @mbggenerated Tue Aug 08 09:36:12 CST 2017
     */
    UserVocab selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_vocab
     *
     * @mbggenerated Tue Aug 08 09:36:12 CST 2017
     */
    int updateByPrimaryKeySelective(UserVocab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_vocab
     *
     * @mbggenerated Tue Aug 08 09:36:12 CST 2017
     */
    int updateByPrimaryKey(UserVocab record);
}