package com.wally.hiread.dao.user;

import com.wally.hiread.model.user.UserPoint;
import com.wally.hiread.model.user.UserPointExample;
import java.util.List;

public interface UserPointMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_user_point
	 * @mbggenerated  Mon May 22 16:31:51 CST 2017
	 */
	int countByExample(UserPointExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_user_point
	 * @mbggenerated  Mon May 22 16:31:51 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_user_point
	 * @mbggenerated  Mon May 22 16:31:51 CST 2017
	 */
	int insert(UserPoint record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_user_point
	 * @mbggenerated  Mon May 22 16:31:51 CST 2017
	 */
	int insertSelective(UserPoint record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_user_point
	 * @mbggenerated  Mon May 22 16:31:51 CST 2017
	 */
	List<UserPoint> selectByExample(UserPointExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_user_point
	 * @mbggenerated  Mon May 22 16:31:51 CST 2017
	 */
	UserPoint selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_user_point
	 * @mbggenerated  Mon May 22 16:31:51 CST 2017
	 */
	int updateByPrimaryKeySelective(UserPoint record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_user_point
	 * @mbggenerated  Mon May 22 16:31:51 CST 2017
	 */
	int updateByPrimaryKey(UserPoint record);
}