package com.wally.hiread.dao.user;

import com.wally.hiread.model.user.User;
import com.wally.hiread.model.user.UserExample;

import java.util.List;
import java.util.Map;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_user
	 * @mbggenerated  Fri Sep 08 17:06:47 CST 2017
	 */
	int countByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_user
	 * @mbggenerated  Fri Sep 08 17:06:47 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_user
	 * @mbggenerated  Fri Sep 08 17:06:47 CST 2017
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_user
	 * @mbggenerated  Fri Sep 08 17:06:47 CST 2017
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_user
	 * @mbggenerated  Fri Sep 08 17:06:47 CST 2017
	 */
	List<User> selectByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_user
	 * @mbggenerated  Fri Sep 08 17:06:47 CST 2017
	 */
	User selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_user
	 * @mbggenerated  Fri Sep 08 17:06:47 CST 2017
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_fd_ec_user
	 * @mbggenerated  Fri Sep 08 17:06:47 CST 2017
	 */
	int updateByPrimaryKey(User record);

	List<User> selectBadgeCount(Map<String,String> params);
}