package com.wally.hiread.model.sys;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WxmpExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_fd_ec_wxmp
     *
     * @mbggenerated Tue Jun 06 16:59:01 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_fd_ec_wxmp
     *
     * @mbggenerated Tue Jun 06 16:59:01 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_fd_ec_wxmp
     *
     * @mbggenerated Tue Jun 06 16:59:01 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_wxmp
     *
     * @mbggenerated Tue Jun 06 16:59:01 CST 2017
     */
    public WxmpExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_wxmp
     *
     * @mbggenerated Tue Jun 06 16:59:01 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_wxmp
     *
     * @mbggenerated Tue Jun 06 16:59:01 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_wxmp
     *
     * @mbggenerated Tue Jun 06 16:59:01 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_wxmp
     *
     * @mbggenerated Tue Jun 06 16:59:01 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_wxmp
     *
     * @mbggenerated Tue Jun 06 16:59:01 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_wxmp
     *
     * @mbggenerated Tue Jun 06 16:59:01 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_wxmp
     *
     * @mbggenerated Tue Jun 06 16:59:01 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_wxmp
     *
     * @mbggenerated Tue Jun 06 16:59:01 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_wxmp
     *
     * @mbggenerated Tue Jun 06 16:59:01 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_wxmp
     *
     * @mbggenerated Tue Jun 06 16:59:01 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_fd_ec_wxmp
     *
     * @mbggenerated Tue Jun 06 16:59:01 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDatecreatedIsNull() {
            addCriterion("dateCreated is null");
            return (Criteria) this;
        }

        public Criteria andDatecreatedIsNotNull() {
            addCriterion("dateCreated is not null");
            return (Criteria) this;
        }

        public Criteria andDatecreatedEqualTo(Date value) {
            addCriterion("dateCreated =", value, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatecreatedNotEqualTo(Date value) {
            addCriterion("dateCreated <>", value, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatecreatedGreaterThan(Date value) {
            addCriterion("dateCreated >", value, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatecreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("dateCreated >=", value, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatecreatedLessThan(Date value) {
            addCriterion("dateCreated <", value, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatecreatedLessThanOrEqualTo(Date value) {
            addCriterion("dateCreated <=", value, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatecreatedIn(List<Date> values) {
            addCriterion("dateCreated in", values, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatecreatedNotIn(List<Date> values) {
            addCriterion("dateCreated not in", values, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatecreatedBetween(Date value1, Date value2) {
            addCriterion("dateCreated between", value1, value2, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatecreatedNotBetween(Date value1, Date value2) {
            addCriterion("dateCreated not between", value1, value2, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedIsNull() {
            addCriterion("dateModified is null");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedIsNotNull() {
            addCriterion("dateModified is not null");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedEqualTo(Date value) {
            addCriterion("dateModified =", value, "datemodified");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedNotEqualTo(Date value) {
            addCriterion("dateModified <>", value, "datemodified");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedGreaterThan(Date value) {
            addCriterion("dateModified >", value, "datemodified");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("dateModified >=", value, "datemodified");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedLessThan(Date value) {
            addCriterion("dateModified <", value, "datemodified");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedLessThanOrEqualTo(Date value) {
            addCriterion("dateModified <=", value, "datemodified");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedIn(List<Date> values) {
            addCriterion("dateModified in", values, "datemodified");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedNotIn(List<Date> values) {
            addCriterion("dateModified not in", values, "datemodified");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedBetween(Date value1, Date value2) {
            addCriterion("dateModified between", value1, value2, "datemodified");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedNotBetween(Date value1, Date value2) {
            addCriterion("dateModified not between", value1, value2, "datemodified");
            return (Criteria) this;
        }

        public Criteria andAtDateCreatedIsNull() {
            addCriterion("c_atDateCreated is null");
            return (Criteria) this;
        }

        public Criteria andAtDateCreatedIsNotNull() {
            addCriterion("c_atDateCreated is not null");
            return (Criteria) this;
        }

        public Criteria andAtDateCreatedEqualTo(String value) {
            addCriterion("c_atDateCreated =", value, "atDateCreated");
            return (Criteria) this;
        }

        public Criteria andAtDateCreatedNotEqualTo(String value) {
            addCriterion("c_atDateCreated <>", value, "atDateCreated");
            return (Criteria) this;
        }

        public Criteria andAtDateCreatedGreaterThan(String value) {
            addCriterion("c_atDateCreated >", value, "atDateCreated");
            return (Criteria) this;
        }

        public Criteria andAtDateCreatedGreaterThanOrEqualTo(String value) {
            addCriterion("c_atDateCreated >=", value, "atDateCreated");
            return (Criteria) this;
        }

        public Criteria andAtDateCreatedLessThan(String value) {
            addCriterion("c_atDateCreated <", value, "atDateCreated");
            return (Criteria) this;
        }

        public Criteria andAtDateCreatedLessThanOrEqualTo(String value) {
            addCriterion("c_atDateCreated <=", value, "atDateCreated");
            return (Criteria) this;
        }

        public Criteria andAtDateCreatedLike(String value) {
            addCriterion("c_atDateCreated like", value, "atDateCreated");
            return (Criteria) this;
        }

        public Criteria andAtDateCreatedNotLike(String value) {
            addCriterion("c_atDateCreated not like", value, "atDateCreated");
            return (Criteria) this;
        }

        public Criteria andAtDateCreatedIn(List<String> values) {
            addCriterion("c_atDateCreated in", values, "atDateCreated");
            return (Criteria) this;
        }

        public Criteria andAtDateCreatedNotIn(List<String> values) {
            addCriterion("c_atDateCreated not in", values, "atDateCreated");
            return (Criteria) this;
        }

        public Criteria andAtDateCreatedBetween(String value1, String value2) {
            addCriterion("c_atDateCreated between", value1, value2, "atDateCreated");
            return (Criteria) this;
        }

        public Criteria andAtDateCreatedNotBetween(String value1, String value2) {
            addCriterion("c_atDateCreated not between", value1, value2, "atDateCreated");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketIsNull() {
            addCriterion("c_jsapiTicket is null");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketIsNotNull() {
            addCriterion("c_jsapiTicket is not null");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketEqualTo(String value) {
            addCriterion("c_jsapiTicket =", value, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketNotEqualTo(String value) {
            addCriterion("c_jsapiTicket <>", value, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketGreaterThan(String value) {
            addCriterion("c_jsapiTicket >", value, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketGreaterThanOrEqualTo(String value) {
            addCriterion("c_jsapiTicket >=", value, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketLessThan(String value) {
            addCriterion("c_jsapiTicket <", value, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketLessThanOrEqualTo(String value) {
            addCriterion("c_jsapiTicket <=", value, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketLike(String value) {
            addCriterion("c_jsapiTicket like", value, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketNotLike(String value) {
            addCriterion("c_jsapiTicket not like", value, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketIn(List<String> values) {
            addCriterion("c_jsapiTicket in", values, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketNotIn(List<String> values) {
            addCriterion("c_jsapiTicket not in", values, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketBetween(String value1, String value2) {
            addCriterion("c_jsapiTicket between", value1, value2, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketNotBetween(String value1, String value2) {
            addCriterion("c_jsapiTicket not between", value1, value2, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJtDateCreatedIsNull() {
            addCriterion("c_jtDateCreated is null");
            return (Criteria) this;
        }

        public Criteria andJtDateCreatedIsNotNull() {
            addCriterion("c_jtDateCreated is not null");
            return (Criteria) this;
        }

        public Criteria andJtDateCreatedEqualTo(String value) {
            addCriterion("c_jtDateCreated =", value, "jtDateCreated");
            return (Criteria) this;
        }

        public Criteria andJtDateCreatedNotEqualTo(String value) {
            addCriterion("c_jtDateCreated <>", value, "jtDateCreated");
            return (Criteria) this;
        }

        public Criteria andJtDateCreatedGreaterThan(String value) {
            addCriterion("c_jtDateCreated >", value, "jtDateCreated");
            return (Criteria) this;
        }

        public Criteria andJtDateCreatedGreaterThanOrEqualTo(String value) {
            addCriterion("c_jtDateCreated >=", value, "jtDateCreated");
            return (Criteria) this;
        }

        public Criteria andJtDateCreatedLessThan(String value) {
            addCriterion("c_jtDateCreated <", value, "jtDateCreated");
            return (Criteria) this;
        }

        public Criteria andJtDateCreatedLessThanOrEqualTo(String value) {
            addCriterion("c_jtDateCreated <=", value, "jtDateCreated");
            return (Criteria) this;
        }

        public Criteria andJtDateCreatedLike(String value) {
            addCriterion("c_jtDateCreated like", value, "jtDateCreated");
            return (Criteria) this;
        }

        public Criteria andJtDateCreatedNotLike(String value) {
            addCriterion("c_jtDateCreated not like", value, "jtDateCreated");
            return (Criteria) this;
        }

        public Criteria andJtDateCreatedIn(List<String> values) {
            addCriterion("c_jtDateCreated in", values, "jtDateCreated");
            return (Criteria) this;
        }

        public Criteria andJtDateCreatedNotIn(List<String> values) {
            addCriterion("c_jtDateCreated not in", values, "jtDateCreated");
            return (Criteria) this;
        }

        public Criteria andJtDateCreatedBetween(String value1, String value2) {
            addCriterion("c_jtDateCreated between", value1, value2, "jtDateCreated");
            return (Criteria) this;
        }

        public Criteria andJtDateCreatedNotBetween(String value1, String value2) {
            addCriterion("c_jtDateCreated not between", value1, value2, "jtDateCreated");
            return (Criteria) this;
        }

        public Criteria andAtExpireInIsNull() {
            addCriterion("c_atExpireIn is null");
            return (Criteria) this;
        }

        public Criteria andAtExpireInIsNotNull() {
            addCriterion("c_atExpireIn is not null");
            return (Criteria) this;
        }

        public Criteria andAtExpireInEqualTo(String value) {
            addCriterion("c_atExpireIn =", value, "atExpireIn");
            return (Criteria) this;
        }

        public Criteria andAtExpireInNotEqualTo(String value) {
            addCriterion("c_atExpireIn <>", value, "atExpireIn");
            return (Criteria) this;
        }

        public Criteria andAtExpireInGreaterThan(String value) {
            addCriterion("c_atExpireIn >", value, "atExpireIn");
            return (Criteria) this;
        }

        public Criteria andAtExpireInGreaterThanOrEqualTo(String value) {
            addCriterion("c_atExpireIn >=", value, "atExpireIn");
            return (Criteria) this;
        }

        public Criteria andAtExpireInLessThan(String value) {
            addCriterion("c_atExpireIn <", value, "atExpireIn");
            return (Criteria) this;
        }

        public Criteria andAtExpireInLessThanOrEqualTo(String value) {
            addCriterion("c_atExpireIn <=", value, "atExpireIn");
            return (Criteria) this;
        }

        public Criteria andAtExpireInLike(String value) {
            addCriterion("c_atExpireIn like", value, "atExpireIn");
            return (Criteria) this;
        }

        public Criteria andAtExpireInNotLike(String value) {
            addCriterion("c_atExpireIn not like", value, "atExpireIn");
            return (Criteria) this;
        }

        public Criteria andAtExpireInIn(List<String> values) {
            addCriterion("c_atExpireIn in", values, "atExpireIn");
            return (Criteria) this;
        }

        public Criteria andAtExpireInNotIn(List<String> values) {
            addCriterion("c_atExpireIn not in", values, "atExpireIn");
            return (Criteria) this;
        }

        public Criteria andAtExpireInBetween(String value1, String value2) {
            addCriterion("c_atExpireIn between", value1, value2, "atExpireIn");
            return (Criteria) this;
        }

        public Criteria andAtExpireInNotBetween(String value1, String value2) {
            addCriterion("c_atExpireIn not between", value1, value2, "atExpireIn");
            return (Criteria) this;
        }

        public Criteria andAtDateModifiedIsNull() {
            addCriterion("c_atDateModified is null");
            return (Criteria) this;
        }

        public Criteria andAtDateModifiedIsNotNull() {
            addCriterion("c_atDateModified is not null");
            return (Criteria) this;
        }

        public Criteria andAtDateModifiedEqualTo(String value) {
            addCriterion("c_atDateModified =", value, "atDateModified");
            return (Criteria) this;
        }

        public Criteria andAtDateModifiedNotEqualTo(String value) {
            addCriterion("c_atDateModified <>", value, "atDateModified");
            return (Criteria) this;
        }

        public Criteria andAtDateModifiedGreaterThan(String value) {
            addCriterion("c_atDateModified >", value, "atDateModified");
            return (Criteria) this;
        }

        public Criteria andAtDateModifiedGreaterThanOrEqualTo(String value) {
            addCriterion("c_atDateModified >=", value, "atDateModified");
            return (Criteria) this;
        }

        public Criteria andAtDateModifiedLessThan(String value) {
            addCriterion("c_atDateModified <", value, "atDateModified");
            return (Criteria) this;
        }

        public Criteria andAtDateModifiedLessThanOrEqualTo(String value) {
            addCriterion("c_atDateModified <=", value, "atDateModified");
            return (Criteria) this;
        }

        public Criteria andAtDateModifiedLike(String value) {
            addCriterion("c_atDateModified like", value, "atDateModified");
            return (Criteria) this;
        }

        public Criteria andAtDateModifiedNotLike(String value) {
            addCriterion("c_atDateModified not like", value, "atDateModified");
            return (Criteria) this;
        }

        public Criteria andAtDateModifiedIn(List<String> values) {
            addCriterion("c_atDateModified in", values, "atDateModified");
            return (Criteria) this;
        }

        public Criteria andAtDateModifiedNotIn(List<String> values) {
            addCriterion("c_atDateModified not in", values, "atDateModified");
            return (Criteria) this;
        }

        public Criteria andAtDateModifiedBetween(String value1, String value2) {
            addCriterion("c_atDateModified between", value1, value2, "atDateModified");
            return (Criteria) this;
        }

        public Criteria andAtDateModifiedNotBetween(String value1, String value2) {
            addCriterion("c_atDateModified not between", value1, value2, "atDateModified");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIsNull() {
            addCriterion("c_accessToken is null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIsNotNull() {
            addCriterion("c_accessToken is not null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenEqualTo(String value) {
            addCriterion("c_accessToken =", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenNotEqualTo(String value) {
            addCriterion("c_accessToken <>", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenGreaterThan(String value) {
            addCriterion("c_accessToken >", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenGreaterThanOrEqualTo(String value) {
            addCriterion("c_accessToken >=", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenLessThan(String value) {
            addCriterion("c_accessToken <", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenLessThanOrEqualTo(String value) {
            addCriterion("c_accessToken <=", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenLike(String value) {
            addCriterion("c_accessToken like", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenNotLike(String value) {
            addCriterion("c_accessToken not like", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIn(List<String> values) {
            addCriterion("c_accessToken in", values, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenNotIn(List<String> values) {
            addCriterion("c_accessToken not in", values, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenBetween(String value1, String value2) {
            addCriterion("c_accessToken between", value1, value2, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenNotBetween(String value1, String value2) {
            addCriterion("c_accessToken not between", value1, value2, "accessToken");
            return (Criteria) this;
        }

        public Criteria andJtDateModifiedIsNull() {
            addCriterion("c_jtDateModified is null");
            return (Criteria) this;
        }

        public Criteria andJtDateModifiedIsNotNull() {
            addCriterion("c_jtDateModified is not null");
            return (Criteria) this;
        }

        public Criteria andJtDateModifiedEqualTo(String value) {
            addCriterion("c_jtDateModified =", value, "jtDateModified");
            return (Criteria) this;
        }

        public Criteria andJtDateModifiedNotEqualTo(String value) {
            addCriterion("c_jtDateModified <>", value, "jtDateModified");
            return (Criteria) this;
        }

        public Criteria andJtDateModifiedGreaterThan(String value) {
            addCriterion("c_jtDateModified >", value, "jtDateModified");
            return (Criteria) this;
        }

        public Criteria andJtDateModifiedGreaterThanOrEqualTo(String value) {
            addCriterion("c_jtDateModified >=", value, "jtDateModified");
            return (Criteria) this;
        }

        public Criteria andJtDateModifiedLessThan(String value) {
            addCriterion("c_jtDateModified <", value, "jtDateModified");
            return (Criteria) this;
        }

        public Criteria andJtDateModifiedLessThanOrEqualTo(String value) {
            addCriterion("c_jtDateModified <=", value, "jtDateModified");
            return (Criteria) this;
        }

        public Criteria andJtDateModifiedLike(String value) {
            addCriterion("c_jtDateModified like", value, "jtDateModified");
            return (Criteria) this;
        }

        public Criteria andJtDateModifiedNotLike(String value) {
            addCriterion("c_jtDateModified not like", value, "jtDateModified");
            return (Criteria) this;
        }

        public Criteria andJtDateModifiedIn(List<String> values) {
            addCriterion("c_jtDateModified in", values, "jtDateModified");
            return (Criteria) this;
        }

        public Criteria andJtDateModifiedNotIn(List<String> values) {
            addCriterion("c_jtDateModified not in", values, "jtDateModified");
            return (Criteria) this;
        }

        public Criteria andJtDateModifiedBetween(String value1, String value2) {
            addCriterion("c_jtDateModified between", value1, value2, "jtDateModified");
            return (Criteria) this;
        }

        public Criteria andJtDateModifiedNotBetween(String value1, String value2) {
            addCriterion("c_jtDateModified not between", value1, value2, "jtDateModified");
            return (Criteria) this;
        }

        public Criteria andJtExpireInIsNull() {
            addCriterion("c_jtExpireIn is null");
            return (Criteria) this;
        }

        public Criteria andJtExpireInIsNotNull() {
            addCriterion("c_jtExpireIn is not null");
            return (Criteria) this;
        }

        public Criteria andJtExpireInEqualTo(String value) {
            addCriterion("c_jtExpireIn =", value, "jtExpireIn");
            return (Criteria) this;
        }

        public Criteria andJtExpireInNotEqualTo(String value) {
            addCriterion("c_jtExpireIn <>", value, "jtExpireIn");
            return (Criteria) this;
        }

        public Criteria andJtExpireInGreaterThan(String value) {
            addCriterion("c_jtExpireIn >", value, "jtExpireIn");
            return (Criteria) this;
        }

        public Criteria andJtExpireInGreaterThanOrEqualTo(String value) {
            addCriterion("c_jtExpireIn >=", value, "jtExpireIn");
            return (Criteria) this;
        }

        public Criteria andJtExpireInLessThan(String value) {
            addCriterion("c_jtExpireIn <", value, "jtExpireIn");
            return (Criteria) this;
        }

        public Criteria andJtExpireInLessThanOrEqualTo(String value) {
            addCriterion("c_jtExpireIn <=", value, "jtExpireIn");
            return (Criteria) this;
        }

        public Criteria andJtExpireInLike(String value) {
            addCriterion("c_jtExpireIn like", value, "jtExpireIn");
            return (Criteria) this;
        }

        public Criteria andJtExpireInNotLike(String value) {
            addCriterion("c_jtExpireIn not like", value, "jtExpireIn");
            return (Criteria) this;
        }

        public Criteria andJtExpireInIn(List<String> values) {
            addCriterion("c_jtExpireIn in", values, "jtExpireIn");
            return (Criteria) this;
        }

        public Criteria andJtExpireInNotIn(List<String> values) {
            addCriterion("c_jtExpireIn not in", values, "jtExpireIn");
            return (Criteria) this;
        }

        public Criteria andJtExpireInBetween(String value1, String value2) {
            addCriterion("c_jtExpireIn between", value1, value2, "jtExpireIn");
            return (Criteria) this;
        }

        public Criteria andJtExpireInNotBetween(String value1, String value2) {
            addCriterion("c_jtExpireIn not between", value1, value2, "jtExpireIn");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_fd_ec_wxmp
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 06 16:59:01 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_fd_ec_wxmp
     *
     * @mbggenerated Tue Jun 06 16:59:01 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}