package com.wally.hiread.model.user;

import java.util.Date;

public class StudyPoint {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_study_point.id
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_study_point.dateCreated
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	private Date datecreated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_study_point.dateModified
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	private Date datemodified;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_study_point.c_reference_id
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	private String referenceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_study_point.c_user_id
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_study_point.c_eventType
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	private String eventType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_study_point.c_point
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	private String point;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_study_point.id
	 * @return  the value of app_fd_ec_study_point.id
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_study_point.id
	 * @param id  the value for app_fd_ec_study_point.id
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_study_point.dateCreated
	 * @return  the value of app_fd_ec_study_point.dateCreated
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	public Date getDatecreated() {
		return datecreated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_study_point.dateCreated
	 * @param datecreated  the value for app_fd_ec_study_point.dateCreated
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_study_point.dateModified
	 * @return  the value of app_fd_ec_study_point.dateModified
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	public Date getDatemodified() {
		return datemodified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_study_point.dateModified
	 * @param datemodified  the value for app_fd_ec_study_point.dateModified
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_study_point.c_reference_id
	 * @return  the value of app_fd_ec_study_point.c_reference_id
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	public String getReferenceId() {
		return referenceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_study_point.c_reference_id
	 * @param referenceId  the value for app_fd_ec_study_point.c_reference_id
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	public void setReferenceId(String referenceId) {
		this.referenceId = referenceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_study_point.c_user_id
	 * @return  the value of app_fd_ec_study_point.c_user_id
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_study_point.c_user_id
	 * @param userId  the value for app_fd_ec_study_point.c_user_id
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_study_point.c_eventType
	 * @return  the value of app_fd_ec_study_point.c_eventType
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	public String getEventType() {
		return eventType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_study_point.c_eventType
	 * @param eventType  the value for app_fd_ec_study_point.c_eventType
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	public void setEventType(String eventType) {
		this.eventType = eventType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_study_point.c_point
	 * @return  the value of app_fd_ec_study_point.c_point
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	public String getPoint() {
		return point;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_study_point.c_point
	 * @param point  the value for app_fd_ec_study_point.c_point
	 * @mbggenerated  Mon May 22 16:55:35 CST 2017
	 */
	public void setPoint(String point) {
		this.point = point;
	}
}