package com.wally.hiread.model.user;

import java.util.Date;

public class UserBadge {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_user_badges.id
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_user_badges.dateCreated
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	private Date datecreated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_user_badges.dateModified
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	private Date datemodified;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_user_badges.c_practise_user_id
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	private String practiseUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_user_badges.c_user_id
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_user_badges.c_subject
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	private String subject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_user_badges.c_product_id
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	private String productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_user_badges.c_getDate
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	private String getDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_user_badges.c_category
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	private String category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_user_badges.c_type
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_user_badges.c_unit_id
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	private String unitId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_user_badges.c_accurateNum
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	private String accurateNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_user_badges.c_unitSection
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	private String unitSection;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_fd_ec_user_badges.c_greatStartType
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	private String greatStartType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_user_badges.id
	 * @return  the value of app_fd_ec_user_badges.id
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_user_badges.id
	 * @param id  the value for app_fd_ec_user_badges.id
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_user_badges.dateCreated
	 * @return  the value of app_fd_ec_user_badges.dateCreated
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public Date getDatecreated() {
		return datecreated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_user_badges.dateCreated
	 * @param datecreated  the value for app_fd_ec_user_badges.dateCreated
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_user_badges.dateModified
	 * @return  the value of app_fd_ec_user_badges.dateModified
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public Date getDatemodified() {
		return datemodified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_user_badges.dateModified
	 * @param datemodified  the value for app_fd_ec_user_badges.dateModified
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_user_badges.c_practise_user_id
	 * @return  the value of app_fd_ec_user_badges.c_practise_user_id
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public String getPractiseUserId() {
		return practiseUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_user_badges.c_practise_user_id
	 * @param practiseUserId  the value for app_fd_ec_user_badges.c_practise_user_id
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public void setPractiseUserId(String practiseUserId) {
		this.practiseUserId = practiseUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_user_badges.c_user_id
	 * @return  the value of app_fd_ec_user_badges.c_user_id
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_user_badges.c_user_id
	 * @param userId  the value for app_fd_ec_user_badges.c_user_id
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_user_badges.c_subject
	 * @return  the value of app_fd_ec_user_badges.c_subject
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public String getSubject() {
		return subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_user_badges.c_subject
	 * @param subject  the value for app_fd_ec_user_badges.c_subject
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_user_badges.c_product_id
	 * @return  the value of app_fd_ec_user_badges.c_product_id
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public String getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_user_badges.c_product_id
	 * @param productId  the value for app_fd_ec_user_badges.c_product_id
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public void setProductId(String productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_user_badges.c_getDate
	 * @return  the value of app_fd_ec_user_badges.c_getDate
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public String getGetDate() {
		return getDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_user_badges.c_getDate
	 * @param getDate  the value for app_fd_ec_user_badges.c_getDate
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public void setGetDate(String getDate) {
		this.getDate = getDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_user_badges.c_category
	 * @return  the value of app_fd_ec_user_badges.c_category
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_user_badges.c_category
	 * @param category  the value for app_fd_ec_user_badges.c_category
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public void setCategory(String category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_user_badges.c_type
	 * @return  the value of app_fd_ec_user_badges.c_type
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_user_badges.c_type
	 * @param type  the value for app_fd_ec_user_badges.c_type
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_user_badges.c_unit_id
	 * @return  the value of app_fd_ec_user_badges.c_unit_id
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public String getUnitId() {
		return unitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_user_badges.c_unit_id
	 * @param unitId  the value for app_fd_ec_user_badges.c_unit_id
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public void setUnitId(String unitId) {
		this.unitId = unitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_user_badges.c_accurateNum
	 * @return  the value of app_fd_ec_user_badges.c_accurateNum
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public String getAccurateNum() {
		return accurateNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_user_badges.c_accurateNum
	 * @param accurateNum  the value for app_fd_ec_user_badges.c_accurateNum
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public void setAccurateNum(String accurateNum) {
		this.accurateNum = accurateNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_user_badges.c_unitSection
	 * @return  the value of app_fd_ec_user_badges.c_unitSection
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public String getUnitSection() {
		return unitSection;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_user_badges.c_unitSection
	 * @param unitSection  the value for app_fd_ec_user_badges.c_unitSection
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public void setUnitSection(String unitSection) {
		this.unitSection = unitSection;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_fd_ec_user_badges.c_greatStartType
	 * @return  the value of app_fd_ec_user_badges.c_greatStartType
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public String getGreatStartType() {
		return greatStartType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_fd_ec_user_badges.c_greatStartType
	 * @param greatStartType  the value for app_fd_ec_user_badges.c_greatStartType
	 * @mbggenerated  Mon Sep 18 11:09:52 CST 2017
	 */
	public void setGreatStartType(String greatStartType) {
		this.greatStartType = greatStartType;
	}

	public static final String CATEGORY_ACADEMIC="academic";
	public static final String CATEGORY_BEHAVIOR="behavior";

	public static final String TYPE_UNIT_COMPLETE="unitComplete";
	public static final String TYPE_ACCURATE="accurate";
	public static final String TYPE_ACCURATE_ADDITIONAL="accurateAdditional";
	public static final String TYPE_SUBJECT_SPECIALIST="subjectSpecialist";

	public static final String TYPE_DAILY_STUDY="dailyStudy";
	public static final String TYPE_CONSISTENT="consistent";
	public static final String TYPE_GREAT_START="greatStart";
	public static final String TYPE_DAILY_RECORDING="dailyRecording";
	public static final String TYPE_CONSISTENT_RECORDING="consistentRecording";

	public static final String TYPE_ACCURATE_NUM="accurateNum";

	public static final String GREATE_START_TYPE_DAILY_RECORDING="dailyRecording";
	public static final String GREATE_START_TYPE_PRACTISE="practise";
	public static final String GREATE_START_TYPE_FREE_TALK="freeTalk";
	public static final String GREATE_START_TYPE_PREVIEW="preview";
	public static final String GREATE_START_TYPE_VIDEO="video";
	private int count;

	public int getCount() {
		return count;
	}

	public void setCount(int count) {
		this.count = count;
	}
}