package com.wally.hiread.model.user;

import java.util.Date;

public class UserTesting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_user_testing.id
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_user_testing.dateCreated
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    private Date datecreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_user_testing.dateModified
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    private Date datemodified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_user_testing.c_answer
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_user_testing.c_correct
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    private String correct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_user_testing.c_user_id
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_fd_ec_user_testing.c_testing_id
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    private String testingId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_user_testing.id
     *
     * @return the value of app_fd_ec_user_testing.id
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_user_testing.id
     *
     * @param id the value for app_fd_ec_user_testing.id
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_user_testing.dateCreated
     *
     * @return the value of app_fd_ec_user_testing.dateCreated
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    public Date getDatecreated() {
        return datecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_user_testing.dateCreated
     *
     * @param datecreated the value for app_fd_ec_user_testing.dateCreated
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    public void setDatecreated(Date datecreated) {
        this.datecreated = datecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_user_testing.dateModified
     *
     * @return the value of app_fd_ec_user_testing.dateModified
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    public Date getDatemodified() {
        return datemodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_user_testing.dateModified
     *
     * @param datemodified the value for app_fd_ec_user_testing.dateModified
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    public void setDatemodified(Date datemodified) {
        this.datemodified = datemodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_user_testing.c_answer
     *
     * @return the value of app_fd_ec_user_testing.c_answer
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_user_testing.c_answer
     *
     * @param answer the value for app_fd_ec_user_testing.c_answer
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_user_testing.c_correct
     *
     * @return the value of app_fd_ec_user_testing.c_correct
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    public String getCorrect() {
        return correct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_user_testing.c_correct
     *
     * @param correct the value for app_fd_ec_user_testing.c_correct
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    public void setCorrect(String correct) {
        this.correct = correct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_user_testing.c_user_id
     *
     * @return the value of app_fd_ec_user_testing.c_user_id
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_user_testing.c_user_id
     *
     * @param userId the value for app_fd_ec_user_testing.c_user_id
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_fd_ec_user_testing.c_testing_id
     *
     * @return the value of app_fd_ec_user_testing.c_testing_id
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    public String getTestingId() {
        return testingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_fd_ec_user_testing.c_testing_id
     *
     * @param testingId the value for app_fd_ec_user_testing.c_testing_id
     *
     * @mbggenerated Tue Aug 29 15:47:38 CST 2017
     */
    public void setTestingId(String testingId) {
        this.testingId = testingId;
    }
}