package com.wally.hiread.model.user;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserStudyLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_fd_ec_user_study_log
     *
     * @mbggenerated Tue Jul 11 14:42:57 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_fd_ec_user_study_log
     *
     * @mbggenerated Tue Jul 11 14:42:57 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_fd_ec_user_study_log
     *
     * @mbggenerated Tue Jul 11 14:42:57 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_study_log
     *
     * @mbggenerated Tue Jul 11 14:42:57 CST 2017
     */
    public UserStudyLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_study_log
     *
     * @mbggenerated Tue Jul 11 14:42:57 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_study_log
     *
     * @mbggenerated Tue Jul 11 14:42:57 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_study_log
     *
     * @mbggenerated Tue Jul 11 14:42:57 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_study_log
     *
     * @mbggenerated Tue Jul 11 14:42:57 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_study_log
     *
     * @mbggenerated Tue Jul 11 14:42:57 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_study_log
     *
     * @mbggenerated Tue Jul 11 14:42:57 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_study_log
     *
     * @mbggenerated Tue Jul 11 14:42:57 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_study_log
     *
     * @mbggenerated Tue Jul 11 14:42:57 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_study_log
     *
     * @mbggenerated Tue Jul 11 14:42:57 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_fd_ec_user_study_log
     *
     * @mbggenerated Tue Jul 11 14:42:57 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_fd_ec_user_study_log
     *
     * @mbggenerated Tue Jul 11 14:42:57 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDatecreatedIsNull() {
            addCriterion("dateCreated is null");
            return (Criteria) this;
        }

        public Criteria andDatecreatedIsNotNull() {
            addCriterion("dateCreated is not null");
            return (Criteria) this;
        }

        public Criteria andDatecreatedEqualTo(Date value) {
            addCriterion("dateCreated =", value, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatecreatedNotEqualTo(Date value) {
            addCriterion("dateCreated <>", value, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatecreatedGreaterThan(Date value) {
            addCriterion("dateCreated >", value, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatecreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("dateCreated >=", value, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatecreatedLessThan(Date value) {
            addCriterion("dateCreated <", value, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatecreatedLessThanOrEqualTo(Date value) {
            addCriterion("dateCreated <=", value, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatecreatedIn(List<Date> values) {
            addCriterion("dateCreated in", values, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatecreatedNotIn(List<Date> values) {
            addCriterion("dateCreated not in", values, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatecreatedBetween(Date value1, Date value2) {
            addCriterion("dateCreated between", value1, value2, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatecreatedNotBetween(Date value1, Date value2) {
            addCriterion("dateCreated not between", value1, value2, "datecreated");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedIsNull() {
            addCriterion("dateModified is null");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedIsNotNull() {
            addCriterion("dateModified is not null");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedEqualTo(Date value) {
            addCriterion("dateModified =", value, "datemodified");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedNotEqualTo(Date value) {
            addCriterion("dateModified <>", value, "datemodified");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedGreaterThan(Date value) {
            addCriterion("dateModified >", value, "datemodified");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("dateModified >=", value, "datemodified");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedLessThan(Date value) {
            addCriterion("dateModified <", value, "datemodified");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedLessThanOrEqualTo(Date value) {
            addCriterion("dateModified <=", value, "datemodified");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedIn(List<Date> values) {
            addCriterion("dateModified in", values, "datemodified");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedNotIn(List<Date> values) {
            addCriterion("dateModified not in", values, "datemodified");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedBetween(Date value1, Date value2) {
            addCriterion("dateModified between", value1, value2, "datemodified");
            return (Criteria) this;
        }

        public Criteria andDatemodifiedNotBetween(Date value1, Date value2) {
            addCriterion("dateModified not between", value1, value2, "datemodified");
            return (Criteria) this;
        }

        public Criteria andAnalysisTimeIsNull() {
            addCriterion("c_analysisTime is null");
            return (Criteria) this;
        }

        public Criteria andAnalysisTimeIsNotNull() {
            addCriterion("c_analysisTime is not null");
            return (Criteria) this;
        }

        public Criteria andAnalysisTimeEqualTo(String value) {
            addCriterion("c_analysisTime =", value, "analysisTime");
            return (Criteria) this;
        }

        public Criteria andAnalysisTimeNotEqualTo(String value) {
            addCriterion("c_analysisTime <>", value, "analysisTime");
            return (Criteria) this;
        }

        public Criteria andAnalysisTimeGreaterThan(String value) {
            addCriterion("c_analysisTime >", value, "analysisTime");
            return (Criteria) this;
        }

        public Criteria andAnalysisTimeGreaterThanOrEqualTo(String value) {
            addCriterion("c_analysisTime >=", value, "analysisTime");
            return (Criteria) this;
        }

        public Criteria andAnalysisTimeLessThan(String value) {
            addCriterion("c_analysisTime <", value, "analysisTime");
            return (Criteria) this;
        }

        public Criteria andAnalysisTimeLessThanOrEqualTo(String value) {
            addCriterion("c_analysisTime <=", value, "analysisTime");
            return (Criteria) this;
        }

        public Criteria andAnalysisTimeLike(String value) {
            addCriterion("c_analysisTime like", value, "analysisTime");
            return (Criteria) this;
        }

        public Criteria andAnalysisTimeNotLike(String value) {
            addCriterion("c_analysisTime not like", value, "analysisTime");
            return (Criteria) this;
        }

        public Criteria andAnalysisTimeIn(List<String> values) {
            addCriterion("c_analysisTime in", values, "analysisTime");
            return (Criteria) this;
        }

        public Criteria andAnalysisTimeNotIn(List<String> values) {
            addCriterion("c_analysisTime not in", values, "analysisTime");
            return (Criteria) this;
        }

        public Criteria andAnalysisTimeBetween(String value1, String value2) {
            addCriterion("c_analysisTime between", value1, value2, "analysisTime");
            return (Criteria) this;
        }

        public Criteria andAnalysisTimeNotBetween(String value1, String value2) {
            addCriterion("c_analysisTime not between", value1, value2, "analysisTime");
            return (Criteria) this;
        }

        public Criteria andAnswerTimeIsNull() {
            addCriterion("c_answerTime is null");
            return (Criteria) this;
        }

        public Criteria andAnswerTimeIsNotNull() {
            addCriterion("c_answerTime is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerTimeEqualTo(String value) {
            addCriterion("c_answerTime =", value, "answerTime");
            return (Criteria) this;
        }

        public Criteria andAnswerTimeNotEqualTo(String value) {
            addCriterion("c_answerTime <>", value, "answerTime");
            return (Criteria) this;
        }

        public Criteria andAnswerTimeGreaterThan(String value) {
            addCriterion("c_answerTime >", value, "answerTime");
            return (Criteria) this;
        }

        public Criteria andAnswerTimeGreaterThanOrEqualTo(String value) {
            addCriterion("c_answerTime >=", value, "answerTime");
            return (Criteria) this;
        }

        public Criteria andAnswerTimeLessThan(String value) {
            addCriterion("c_answerTime <", value, "answerTime");
            return (Criteria) this;
        }

        public Criteria andAnswerTimeLessThanOrEqualTo(String value) {
            addCriterion("c_answerTime <=", value, "answerTime");
            return (Criteria) this;
        }

        public Criteria andAnswerTimeLike(String value) {
            addCriterion("c_answerTime like", value, "answerTime");
            return (Criteria) this;
        }

        public Criteria andAnswerTimeNotLike(String value) {
            addCriterion("c_answerTime not like", value, "answerTime");
            return (Criteria) this;
        }

        public Criteria andAnswerTimeIn(List<String> values) {
            addCriterion("c_answerTime in", values, "answerTime");
            return (Criteria) this;
        }

        public Criteria andAnswerTimeNotIn(List<String> values) {
            addCriterion("c_answerTime not in", values, "answerTime");
            return (Criteria) this;
        }

        public Criteria andAnswerTimeBetween(String value1, String value2) {
            addCriterion("c_answerTime between", value1, value2, "answerTime");
            return (Criteria) this;
        }

        public Criteria andAnswerTimeNotBetween(String value1, String value2) {
            addCriterion("c_answerTime not between", value1, value2, "answerTime");
            return (Criteria) this;
        }

        public Criteria andMediaTimeIsNull() {
            addCriterion("c_mediaTime is null");
            return (Criteria) this;
        }

        public Criteria andMediaTimeIsNotNull() {
            addCriterion("c_mediaTime is not null");
            return (Criteria) this;
        }

        public Criteria andMediaTimeEqualTo(String value) {
            addCriterion("c_mediaTime =", value, "mediaTime");
            return (Criteria) this;
        }

        public Criteria andMediaTimeNotEqualTo(String value) {
            addCriterion("c_mediaTime <>", value, "mediaTime");
            return (Criteria) this;
        }

        public Criteria andMediaTimeGreaterThan(String value) {
            addCriterion("c_mediaTime >", value, "mediaTime");
            return (Criteria) this;
        }

        public Criteria andMediaTimeGreaterThanOrEqualTo(String value) {
            addCriterion("c_mediaTime >=", value, "mediaTime");
            return (Criteria) this;
        }

        public Criteria andMediaTimeLessThan(String value) {
            addCriterion("c_mediaTime <", value, "mediaTime");
            return (Criteria) this;
        }

        public Criteria andMediaTimeLessThanOrEqualTo(String value) {
            addCriterion("c_mediaTime <=", value, "mediaTime");
            return (Criteria) this;
        }

        public Criteria andMediaTimeLike(String value) {
            addCriterion("c_mediaTime like", value, "mediaTime");
            return (Criteria) this;
        }

        public Criteria andMediaTimeNotLike(String value) {
            addCriterion("c_mediaTime not like", value, "mediaTime");
            return (Criteria) this;
        }

        public Criteria andMediaTimeIn(List<String> values) {
            addCriterion("c_mediaTime in", values, "mediaTime");
            return (Criteria) this;
        }

        public Criteria andMediaTimeNotIn(List<String> values) {
            addCriterion("c_mediaTime not in", values, "mediaTime");
            return (Criteria) this;
        }

        public Criteria andMediaTimeBetween(String value1, String value2) {
            addCriterion("c_mediaTime between", value1, value2, "mediaTime");
            return (Criteria) this;
        }

        public Criteria andMediaTimeNotBetween(String value1, String value2) {
            addCriterion("c_mediaTime not between", value1, value2, "mediaTime");
            return (Criteria) this;
        }

        public Criteria andCompletedIsNull() {
            addCriterion("c_completed is null");
            return (Criteria) this;
        }

        public Criteria andCompletedIsNotNull() {
            addCriterion("c_completed is not null");
            return (Criteria) this;
        }

        public Criteria andCompletedEqualTo(String value) {
            addCriterion("c_completed =", value, "completed");
            return (Criteria) this;
        }

        public Criteria andCompletedNotEqualTo(String value) {
            addCriterion("c_completed <>", value, "completed");
            return (Criteria) this;
        }

        public Criteria andCompletedGreaterThan(String value) {
            addCriterion("c_completed >", value, "completed");
            return (Criteria) this;
        }

        public Criteria andCompletedGreaterThanOrEqualTo(String value) {
            addCriterion("c_completed >=", value, "completed");
            return (Criteria) this;
        }

        public Criteria andCompletedLessThan(String value) {
            addCriterion("c_completed <", value, "completed");
            return (Criteria) this;
        }

        public Criteria andCompletedLessThanOrEqualTo(String value) {
            addCriterion("c_completed <=", value, "completed");
            return (Criteria) this;
        }

        public Criteria andCompletedLike(String value) {
            addCriterion("c_completed like", value, "completed");
            return (Criteria) this;
        }

        public Criteria andCompletedNotLike(String value) {
            addCriterion("c_completed not like", value, "completed");
            return (Criteria) this;
        }

        public Criteria andCompletedIn(List<String> values) {
            addCriterion("c_completed in", values, "completed");
            return (Criteria) this;
        }

        public Criteria andCompletedNotIn(List<String> values) {
            addCriterion("c_completed not in", values, "completed");
            return (Criteria) this;
        }

        public Criteria andCompletedBetween(String value1, String value2) {
            addCriterion("c_completed between", value1, value2, "completed");
            return (Criteria) this;
        }

        public Criteria andCompletedNotBetween(String value1, String value2) {
            addCriterion("c_completed not between", value1, value2, "completed");
            return (Criteria) this;
        }

        public Criteria andStudySectionIsNull() {
            addCriterion("c_studySection is null");
            return (Criteria) this;
        }

        public Criteria andStudySectionIsNotNull() {
            addCriterion("c_studySection is not null");
            return (Criteria) this;
        }

        public Criteria andStudySectionEqualTo(String value) {
            addCriterion("c_studySection =", value, "studySection");
            return (Criteria) this;
        }

        public Criteria andStudySectionNotEqualTo(String value) {
            addCriterion("c_studySection <>", value, "studySection");
            return (Criteria) this;
        }

        public Criteria andStudySectionGreaterThan(String value) {
            addCriterion("c_studySection >", value, "studySection");
            return (Criteria) this;
        }

        public Criteria andStudySectionGreaterThanOrEqualTo(String value) {
            addCriterion("c_studySection >=", value, "studySection");
            return (Criteria) this;
        }

        public Criteria andStudySectionLessThan(String value) {
            addCriterion("c_studySection <", value, "studySection");
            return (Criteria) this;
        }

        public Criteria andStudySectionLessThanOrEqualTo(String value) {
            addCriterion("c_studySection <=", value, "studySection");
            return (Criteria) this;
        }

        public Criteria andStudySectionLike(String value) {
            addCriterion("c_studySection like", value, "studySection");
            return (Criteria) this;
        }

        public Criteria andStudySectionNotLike(String value) {
            addCriterion("c_studySection not like", value, "studySection");
            return (Criteria) this;
        }

        public Criteria andStudySectionIn(List<String> values) {
            addCriterion("c_studySection in", values, "studySection");
            return (Criteria) this;
        }

        public Criteria andStudySectionNotIn(List<String> values) {
            addCriterion("c_studySection not in", values, "studySection");
            return (Criteria) this;
        }

        public Criteria andStudySectionBetween(String value1, String value2) {
            addCriterion("c_studySection between", value1, value2, "studySection");
            return (Criteria) this;
        }

        public Criteria andStudySectionNotBetween(String value1, String value2) {
            addCriterion("c_studySection not between", value1, value2, "studySection");
            return (Criteria) this;
        }

        public Criteria andCompleteNumIsNull() {
            addCriterion("c_completeNum is null");
            return (Criteria) this;
        }

        public Criteria andCompleteNumIsNotNull() {
            addCriterion("c_completeNum is not null");
            return (Criteria) this;
        }

        public Criteria andCompleteNumEqualTo(String value) {
            addCriterion("c_completeNum =", value, "completeNum");
            return (Criteria) this;
        }

        public Criteria andCompleteNumNotEqualTo(String value) {
            addCriterion("c_completeNum <>", value, "completeNum");
            return (Criteria) this;
        }

        public Criteria andCompleteNumGreaterThan(String value) {
            addCriterion("c_completeNum >", value, "completeNum");
            return (Criteria) this;
        }

        public Criteria andCompleteNumGreaterThanOrEqualTo(String value) {
            addCriterion("c_completeNum >=", value, "completeNum");
            return (Criteria) this;
        }

        public Criteria andCompleteNumLessThan(String value) {
            addCriterion("c_completeNum <", value, "completeNum");
            return (Criteria) this;
        }

        public Criteria andCompleteNumLessThanOrEqualTo(String value) {
            addCriterion("c_completeNum <=", value, "completeNum");
            return (Criteria) this;
        }

        public Criteria andCompleteNumLike(String value) {
            addCriterion("c_completeNum like", value, "completeNum");
            return (Criteria) this;
        }

        public Criteria andCompleteNumNotLike(String value) {
            addCriterion("c_completeNum not like", value, "completeNum");
            return (Criteria) this;
        }

        public Criteria andCompleteNumIn(List<String> values) {
            addCriterion("c_completeNum in", values, "completeNum");
            return (Criteria) this;
        }

        public Criteria andCompleteNumNotIn(List<String> values) {
            addCriterion("c_completeNum not in", values, "completeNum");
            return (Criteria) this;
        }

        public Criteria andCompleteNumBetween(String value1, String value2) {
            addCriterion("c_completeNum between", value1, value2, "completeNum");
            return (Criteria) this;
        }

        public Criteria andCompleteNumNotBetween(String value1, String value2) {
            addCriterion("c_completeNum not between", value1, value2, "completeNum");
            return (Criteria) this;
        }

        public Criteria andTimesIsNull() {
            addCriterion("c_times is null");
            return (Criteria) this;
        }

        public Criteria andTimesIsNotNull() {
            addCriterion("c_times is not null");
            return (Criteria) this;
        }

        public Criteria andTimesEqualTo(String value) {
            addCriterion("c_times =", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesNotEqualTo(String value) {
            addCriterion("c_times <>", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesGreaterThan(String value) {
            addCriterion("c_times >", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesGreaterThanOrEqualTo(String value) {
            addCriterion("c_times >=", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesLessThan(String value) {
            addCriterion("c_times <", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesLessThanOrEqualTo(String value) {
            addCriterion("c_times <=", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesLike(String value) {
            addCriterion("c_times like", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesNotLike(String value) {
            addCriterion("c_times not like", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesIn(List<String> values) {
            addCriterion("c_times in", values, "times");
            return (Criteria) this;
        }

        public Criteria andTimesNotIn(List<String> values) {
            addCriterion("c_times not in", values, "times");
            return (Criteria) this;
        }

        public Criteria andTimesBetween(String value1, String value2) {
            addCriterion("c_times between", value1, value2, "times");
            return (Criteria) this;
        }

        public Criteria andTimesNotBetween(String value1, String value2) {
            addCriterion("c_times not between", value1, value2, "times");
            return (Criteria) this;
        }

        public Criteria andPractiseNumIsNull() {
            addCriterion("c_practiseNum is null");
            return (Criteria) this;
        }

        public Criteria andPractiseNumIsNotNull() {
            addCriterion("c_practiseNum is not null");
            return (Criteria) this;
        }

        public Criteria andPractiseNumEqualTo(String value) {
            addCriterion("c_practiseNum =", value, "practiseNum");
            return (Criteria) this;
        }

        public Criteria andPractiseNumNotEqualTo(String value) {
            addCriterion("c_practiseNum <>", value, "practiseNum");
            return (Criteria) this;
        }

        public Criteria andPractiseNumGreaterThan(String value) {
            addCriterion("c_practiseNum >", value, "practiseNum");
            return (Criteria) this;
        }

        public Criteria andPractiseNumGreaterThanOrEqualTo(String value) {
            addCriterion("c_practiseNum >=", value, "practiseNum");
            return (Criteria) this;
        }

        public Criteria andPractiseNumLessThan(String value) {
            addCriterion("c_practiseNum <", value, "practiseNum");
            return (Criteria) this;
        }

        public Criteria andPractiseNumLessThanOrEqualTo(String value) {
            addCriterion("c_practiseNum <=", value, "practiseNum");
            return (Criteria) this;
        }

        public Criteria andPractiseNumLike(String value) {
            addCriterion("c_practiseNum like", value, "practiseNum");
            return (Criteria) this;
        }

        public Criteria andPractiseNumNotLike(String value) {
            addCriterion("c_practiseNum not like", value, "practiseNum");
            return (Criteria) this;
        }

        public Criteria andPractiseNumIn(List<String> values) {
            addCriterion("c_practiseNum in", values, "practiseNum");
            return (Criteria) this;
        }

        public Criteria andPractiseNumNotIn(List<String> values) {
            addCriterion("c_practiseNum not in", values, "practiseNum");
            return (Criteria) this;
        }

        public Criteria andPractiseNumBetween(String value1, String value2) {
            addCriterion("c_practiseNum between", value1, value2, "practiseNum");
            return (Criteria) this;
        }

        public Criteria andPractiseNumNotBetween(String value1, String value2) {
            addCriterion("c_practiseNum not between", value1, value2, "practiseNum");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("c_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("c_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("c_user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("c_user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("c_user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("c_user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("c_user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("c_user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("c_user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("c_user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("c_user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("c_user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("c_user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("c_user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("c_product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("c_product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(String value) {
            addCriterion("c_product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(String value) {
            addCriterion("c_product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(String value) {
            addCriterion("c_product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("c_product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(String value) {
            addCriterion("c_product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(String value) {
            addCriterion("c_product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLike(String value) {
            addCriterion("c_product_id like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotLike(String value) {
            addCriterion("c_product_id not like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<String> values) {
            addCriterion("c_product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<String> values) {
            addCriterion("c_product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(String value1, String value2) {
            addCriterion("c_product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(String value1, String value2) {
            addCriterion("c_product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andStudyDateIsNull() {
            addCriterion("c_studyDate is null");
            return (Criteria) this;
        }

        public Criteria andStudyDateIsNotNull() {
            addCriterion("c_studyDate is not null");
            return (Criteria) this;
        }

        public Criteria andStudyDateEqualTo(String value) {
            addCriterion("c_studyDate =", value, "studyDate");
            return (Criteria) this;
        }

        public Criteria andStudyDateNotEqualTo(String value) {
            addCriterion("c_studyDate <>", value, "studyDate");
            return (Criteria) this;
        }

        public Criteria andStudyDateGreaterThan(String value) {
            addCriterion("c_studyDate >", value, "studyDate");
            return (Criteria) this;
        }

        public Criteria andStudyDateGreaterThanOrEqualTo(String value) {
            addCriterion("c_studyDate >=", value, "studyDate");
            return (Criteria) this;
        }

        public Criteria andStudyDateLessThan(String value) {
            addCriterion("c_studyDate <", value, "studyDate");
            return (Criteria) this;
        }

        public Criteria andStudyDateLessThanOrEqualTo(String value) {
            addCriterion("c_studyDate <=", value, "studyDate");
            return (Criteria) this;
        }

        public Criteria andStudyDateLike(String value) {
            addCriterion("c_studyDate like", value, "studyDate");
            return (Criteria) this;
        }

        public Criteria andStudyDateNotLike(String value) {
            addCriterion("c_studyDate not like", value, "studyDate");
            return (Criteria) this;
        }

        public Criteria andStudyDateIn(List<String> values) {
            addCriterion("c_studyDate in", values, "studyDate");
            return (Criteria) this;
        }

        public Criteria andStudyDateNotIn(List<String> values) {
            addCriterion("c_studyDate not in", values, "studyDate");
            return (Criteria) this;
        }

        public Criteria andStudyDateBetween(String value1, String value2) {
            addCriterion("c_studyDate between", value1, value2, "studyDate");
            return (Criteria) this;
        }

        public Criteria andStudyDateNotBetween(String value1, String value2) {
            addCriterion("c_studyDate not between", value1, value2, "studyDate");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("c_startTime is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("c_startTime is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(String value) {
            addCriterion("c_startTime =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(String value) {
            addCriterion("c_startTime <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(String value) {
            addCriterion("c_startTime >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("c_startTime >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(String value) {
            addCriterion("c_startTime <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(String value) {
            addCriterion("c_startTime <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLike(String value) {
            addCriterion("c_startTime like", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotLike(String value) {
            addCriterion("c_startTime not like", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<String> values) {
            addCriterion("c_startTime in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<String> values) {
            addCriterion("c_startTime not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(String value1, String value2) {
            addCriterion("c_startTime between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(String value1, String value2) {
            addCriterion("c_startTime not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andSnIsNull() {
            addCriterion("c_sn is null");
            return (Criteria) this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("c_sn is not null");
            return (Criteria) this;
        }

        public Criteria andSnEqualTo(String value) {
            addCriterion("c_sn =", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotEqualTo(String value) {
            addCriterion("c_sn <>", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnGreaterThan(String value) {
            addCriterion("c_sn >", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnGreaterThanOrEqualTo(String value) {
            addCriterion("c_sn >=", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnLessThan(String value) {
            addCriterion("c_sn <", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnLessThanOrEqualTo(String value) {
            addCriterion("c_sn <=", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnLike(String value) {
            addCriterion("c_sn like", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotLike(String value) {
            addCriterion("c_sn not like", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnIn(List<String> values) {
            addCriterion("c_sn in", values, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotIn(List<String> values) {
            addCriterion("c_sn not in", values, "sn");
            return (Criteria) this;
        }

        public Criteria andSnBetween(String value1, String value2) {
            addCriterion("c_sn between", value1, value2, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotBetween(String value1, String value2) {
            addCriterion("c_sn not between", value1, value2, "sn");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("c_endTime is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("c_endTime is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(String value) {
            addCriterion("c_endTime =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(String value) {
            addCriterion("c_endTime <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(String value) {
            addCriterion("c_endTime >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("c_endTime >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(String value) {
            addCriterion("c_endTime <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(String value) {
            addCriterion("c_endTime <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLike(String value) {
            addCriterion("c_endTime like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotLike(String value) {
            addCriterion("c_endTime not like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<String> values) {
            addCriterion("c_endTime in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<String> values) {
            addCriterion("c_endTime not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(String value1, String value2) {
            addCriterion("c_endTime between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(String value1, String value2) {
            addCriterion("c_endTime not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andUnitIdIsNull() {
            addCriterion("c_unit_id is null");
            return (Criteria) this;
        }

        public Criteria andUnitIdIsNotNull() {
            addCriterion("c_unit_id is not null");
            return (Criteria) this;
        }

        public Criteria andUnitIdEqualTo(String value) {
            addCriterion("c_unit_id =", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdNotEqualTo(String value) {
            addCriterion("c_unit_id <>", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdGreaterThan(String value) {
            addCriterion("c_unit_id >", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdGreaterThanOrEqualTo(String value) {
            addCriterion("c_unit_id >=", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdLessThan(String value) {
            addCriterion("c_unit_id <", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdLessThanOrEqualTo(String value) {
            addCriterion("c_unit_id <=", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdLike(String value) {
            addCriterion("c_unit_id like", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdNotLike(String value) {
            addCriterion("c_unit_id not like", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdIn(List<String> values) {
            addCriterion("c_unit_id in", values, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdNotIn(List<String> values) {
            addCriterion("c_unit_id not in", values, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdBetween(String value1, String value2) {
            addCriterion("c_unit_id between", value1, value2, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdNotBetween(String value1, String value2) {
            addCriterion("c_unit_id not between", value1, value2, "unitId");
            return (Criteria) this;
        }

        public Criteria andCorrectNumIsNull() {
            addCriterion("c_correctNum is null");
            return (Criteria) this;
        }

        public Criteria andCorrectNumIsNotNull() {
            addCriterion("c_correctNum is not null");
            return (Criteria) this;
        }

        public Criteria andCorrectNumEqualTo(String value) {
            addCriterion("c_correctNum =", value, "correctNum");
            return (Criteria) this;
        }

        public Criteria andCorrectNumNotEqualTo(String value) {
            addCriterion("c_correctNum <>", value, "correctNum");
            return (Criteria) this;
        }

        public Criteria andCorrectNumGreaterThan(String value) {
            addCriterion("c_correctNum >", value, "correctNum");
            return (Criteria) this;
        }

        public Criteria andCorrectNumGreaterThanOrEqualTo(String value) {
            addCriterion("c_correctNum >=", value, "correctNum");
            return (Criteria) this;
        }

        public Criteria andCorrectNumLessThan(String value) {
            addCriterion("c_correctNum <", value, "correctNum");
            return (Criteria) this;
        }

        public Criteria andCorrectNumLessThanOrEqualTo(String value) {
            addCriterion("c_correctNum <=", value, "correctNum");
            return (Criteria) this;
        }

        public Criteria andCorrectNumLike(String value) {
            addCriterion("c_correctNum like", value, "correctNum");
            return (Criteria) this;
        }

        public Criteria andCorrectNumNotLike(String value) {
            addCriterion("c_correctNum not like", value, "correctNum");
            return (Criteria) this;
        }

        public Criteria andCorrectNumIn(List<String> values) {
            addCriterion("c_correctNum in", values, "correctNum");
            return (Criteria) this;
        }

        public Criteria andCorrectNumNotIn(List<String> values) {
            addCriterion("c_correctNum not in", values, "correctNum");
            return (Criteria) this;
        }

        public Criteria andCorrectNumBetween(String value1, String value2) {
            addCriterion("c_correctNum between", value1, value2, "correctNum");
            return (Criteria) this;
        }

        public Criteria andCorrectNumNotBetween(String value1, String value2) {
            addCriterion("c_correctNum not between", value1, value2, "correctNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_fd_ec_user_study_log
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 11 14:42:57 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_fd_ec_user_study_log
     *
     * @mbggenerated Tue Jul 11 14:42:57 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}